'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace CoreWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CoreWSSoap", [Namespace]:="http://www.omnibridge.com/SDKWebServices/Core"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityBase))>  _
    Partial Public Class CoreWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private LoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AdminLoginOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserContextOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserContext_NoMultiSearchOperationCompleted As System.Threading.SendOrPostCallback
        
        Private tokenHeaderValueField As TokenHeader
        
        Private LoadDaylightSavingsSettingsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetCurrentOrgIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetWebServiceURLsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetFunctionsForUserOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUsersForOrganisationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCurrentOrgIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Position_Updater.My.MySettings.Default.Position_Updater_CoreWS_CoreWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property TokenHeaderValue() As TokenHeader
            Get
                Return Me.tokenHeaderValueField
            End Get
            Set
                Me.tokenHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event LoginCompleted As LoginCompletedEventHandler
        
        '''<remarks/>
        Public Event AdminLoginCompleted As AdminLoginCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserContextCompleted As GetUserContextCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserContext_NoMultiSearchCompleted As GetUserContext_NoMultiSearchCompletedEventHandler
        
        '''<remarks/>
        Public Event LoadDaylightSavingsSettingsCompleted As LoadDaylightSavingsSettingsCompletedEventHandler
        
        '''<remarks/>
        Public Event SetCurrentOrgIDCompleted As SetCurrentOrgIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetWebServiceURLsCompleted As GetWebServiceURLsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetFunctionsForUserCompleted As GetFunctionsForUserCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUsersForOrganisationCompleted As GetUsersForOrganisationCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCurrentOrgIDCompleted As GetCurrentOrgIDCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/Login", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Login(ByVal UserName As String, ByVal Password As String, ByVal ApplicationID As String) As WebLoginResult
            Dim results() As Object = Me.Invoke("Login", New Object() {UserName, Password, ApplicationID})
            Return CType(results(0),WebLoginResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal UserName As String, ByVal Password As String, ByVal ApplicationID As String)
            Me.LoginAsync(UserName, Password, ApplicationID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoginAsync(ByVal UserName As String, ByVal Password As String, ByVal ApplicationID As String, ByVal userState As Object)
            If (Me.LoginOperationCompleted Is Nothing) Then
                Me.LoginOperationCompleted = AddressOf Me.OnLoginOperationCompleted
            End If
            Me.InvokeAsync("Login", New Object() {UserName, Password, ApplicationID}, Me.LoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoginCompleted(Me, New LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/AdminLogin", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AdminLogin(ByVal UserName As String, ByVal Password As String, ByVal ApplicationID As String) As WebLoginResult
            Dim results() As Object = Me.Invoke("AdminLogin", New Object() {UserName, Password, ApplicationID})
            Return CType(results(0),WebLoginResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AdminLoginAsync(ByVal UserName As String, ByVal Password As String, ByVal ApplicationID As String)
            Me.AdminLoginAsync(UserName, Password, ApplicationID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AdminLoginAsync(ByVal UserName As String, ByVal Password As String, ByVal ApplicationID As String, ByVal userState As Object)
            If (Me.AdminLoginOperationCompleted Is Nothing) Then
                Me.AdminLoginOperationCompleted = AddressOf Me.OnAdminLoginOperationCompleted
            End If
            Me.InvokeAsync("AdminLogin", New Object() {UserName, Password, ApplicationID}, Me.AdminLoginOperationCompleted, userState)
        End Sub
        
        Private Sub OnAdminLoginOperationCompleted(ByVal arg As Object)
            If (Not (Me.AdminLoginCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AdminLoginCompleted(Me, New AdminLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/GetUserContext", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserContext(ByVal Token As String) As UserContext
            Dim results() As Object = Me.Invoke("GetUserContext", New Object() {Token})
            Return CType(results(0),UserContext)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserContextAsync(ByVal Token As String)
            Me.GetUserContextAsync(Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserContextAsync(ByVal Token As String, ByVal userState As Object)
            If (Me.GetUserContextOperationCompleted Is Nothing) Then
                Me.GetUserContextOperationCompleted = AddressOf Me.OnGetUserContextOperationCompleted
            End If
            Me.InvokeAsync("GetUserContext", New Object() {Token}, Me.GetUserContextOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserContextOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserContextCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserContextCompleted(Me, New GetUserContextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/GetUserContext_NoMultiSearch", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserContext_NoMultiSearch(ByVal Token As String) As UserContext
            Dim results() As Object = Me.Invoke("GetUserContext_NoMultiSearch", New Object() {Token})
            Return CType(results(0),UserContext)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserContext_NoMultiSearchAsync(ByVal Token As String)
            Me.GetUserContext_NoMultiSearchAsync(Token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserContext_NoMultiSearchAsync(ByVal Token As String, ByVal userState As Object)
            If (Me.GetUserContext_NoMultiSearchOperationCompleted Is Nothing) Then
                Me.GetUserContext_NoMultiSearchOperationCompleted = AddressOf Me.OnGetUserContext_NoMultiSearchOperationCompleted
            End If
            Me.InvokeAsync("GetUserContext_NoMultiSearch", New Object() {Token}, Me.GetUserContext_NoMultiSearchOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserContext_NoMultiSearchOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserContext_NoMultiSearchCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserContext_NoMultiSearchCompleted(Me, New GetUserContext_NoMultiSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/LoadDaylightSavingsSettings", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LoadDaylightSavingsSettings() As DaylightSaving
            Dim results() As Object = Me.Invoke("LoadDaylightSavingsSettings", New Object(-1) {})
            Return CType(results(0),DaylightSaving)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LoadDaylightSavingsSettingsAsync()
            Me.LoadDaylightSavingsSettingsAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LoadDaylightSavingsSettingsAsync(ByVal userState As Object)
            If (Me.LoadDaylightSavingsSettingsOperationCompleted Is Nothing) Then
                Me.LoadDaylightSavingsSettingsOperationCompleted = AddressOf Me.OnLoadDaylightSavingsSettingsOperationCompleted
            End If
            Me.InvokeAsync("LoadDaylightSavingsSettings", New Object(-1) {}, Me.LoadDaylightSavingsSettingsOperationCompleted, userState)
        End Sub
        
        Private Sub OnLoadDaylightSavingsSettingsOperationCompleted(ByVal arg As Object)
            If (Not (Me.LoadDaylightSavingsSettingsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LoadDaylightSavingsSettingsCompleted(Me, New LoadDaylightSavingsSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/SetCurrentOrgID", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetCurrentOrgID(ByVal NewOrganisationID As Integer) As UserContext
            Dim results() As Object = Me.Invoke("SetCurrentOrgID", New Object() {NewOrganisationID})
            Return CType(results(0),UserContext)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetCurrentOrgIDAsync(ByVal NewOrganisationID As Integer)
            Me.SetCurrentOrgIDAsync(NewOrganisationID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetCurrentOrgIDAsync(ByVal NewOrganisationID As Integer, ByVal userState As Object)
            If (Me.SetCurrentOrgIDOperationCompleted Is Nothing) Then
                Me.SetCurrentOrgIDOperationCompleted = AddressOf Me.OnSetCurrentOrgIDOperationCompleted
            End If
            Me.InvokeAsync("SetCurrentOrgID", New Object() {NewOrganisationID}, Me.SetCurrentOrgIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetCurrentOrgIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetCurrentOrgIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetCurrentOrgIDCompleted(Me, New SetCurrentOrgIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/GetWebServiceURLs", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetWebServiceURLs(ByVal ApplicationName As String, ByVal Version As String) As WebServiceURL()
            Dim results() As Object = Me.Invoke("GetWebServiceURLs", New Object() {ApplicationName, Version})
            Return CType(results(0),WebServiceURL())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetWebServiceURLsAsync(ByVal ApplicationName As String, ByVal Version As String)
            Me.GetWebServiceURLsAsync(ApplicationName, Version, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetWebServiceURLsAsync(ByVal ApplicationName As String, ByVal Version As String, ByVal userState As Object)
            If (Me.GetWebServiceURLsOperationCompleted Is Nothing) Then
                Me.GetWebServiceURLsOperationCompleted = AddressOf Me.OnGetWebServiceURLsOperationCompleted
            End If
            Me.InvokeAsync("GetWebServiceURLs", New Object() {ApplicationName, Version}, Me.GetWebServiceURLsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetWebServiceURLsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetWebServiceURLsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetWebServiceURLsCompleted(Me, New GetWebServiceURLsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/GetFunctionsForUser", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetFunctionsForUser() As Integer()
            Dim results() As Object = Me.Invoke("GetFunctionsForUser", New Object(-1) {})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetFunctionsForUserAsync()
            Me.GetFunctionsForUserAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetFunctionsForUserAsync(ByVal userState As Object)
            If (Me.GetFunctionsForUserOperationCompleted Is Nothing) Then
                Me.GetFunctionsForUserOperationCompleted = AddressOf Me.OnGetFunctionsForUserOperationCompleted
            End If
            Me.InvokeAsync("GetFunctionsForUser", New Object(-1) {}, Me.GetFunctionsForUserOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetFunctionsForUserOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetFunctionsForUserCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetFunctionsForUserCompleted(Me, New GetFunctionsForUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/GetUsersForOrganisation", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUsersForOrganisation(ByVal OrganisationID As Integer) As User()
            Dim results() As Object = Me.Invoke("GetUsersForOrganisation", New Object() {OrganisationID})
            Return CType(results(0),User())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUsersForOrganisationAsync(ByVal OrganisationID As Integer)
            Me.GetUsersForOrganisationAsync(OrganisationID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUsersForOrganisationAsync(ByVal OrganisationID As Integer, ByVal userState As Object)
            If (Me.GetUsersForOrganisationOperationCompleted Is Nothing) Then
                Me.GetUsersForOrganisationOperationCompleted = AddressOf Me.OnGetUsersForOrganisationOperationCompleted
            End If
            Me.InvokeAsync("GetUsersForOrganisation", New Object() {OrganisationID}, Me.GetUsersForOrganisationOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUsersForOrganisationOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUsersForOrganisationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUsersForOrganisationCompleted(Me, New GetUsersForOrganisationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Core/GetCurrentOrgID", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Core", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Core", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCurrentOrgID() As Integer
            Dim results() As Object = Me.Invoke("GetCurrentOrgID", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCurrentOrgIDAsync()
            Me.GetCurrentOrgIDAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCurrentOrgIDAsync(ByVal userState As Object)
            If (Me.GetCurrentOrgIDOperationCompleted Is Nothing) Then
                Me.GetCurrentOrgIDOperationCompleted = AddressOf Me.OnGetCurrentOrgIDOperationCompleted
            End If
            Me.InvokeAsync("GetCurrentOrgID", New Object(-1) {}, Me.GetCurrentOrgIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCurrentOrgIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCurrentOrgIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCurrentOrgIDCompleted(Me, New GetCurrentOrgIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core", IsNullable:=false)>  _
    Partial Public Class TokenHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private tokenField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class WebServiceURL
        
        Private nameField As String
        
        Private urlField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class TimeSpan
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(DaylightSaving)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Organisation)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType([Function])),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(UIView)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(User)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public MustInherit Class EntityBase
        
        Private idField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class DaylightSaving
        Inherits EntityBase
        
        Private enabledField As Boolean
        
        Private startField As Date
        
        Private endField As Date
        
        Private adjustSecondsField As Integer
        
        '''<remarks/>
        Public Property Enabled() As Boolean
            Get
                Return Me.enabledField
            End Get
            Set
                Me.enabledField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Start() As Date
            Get
                Return Me.startField
            End Get
            Set
                Me.startField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [End]() As Date
            Get
                Return Me.endField
            End Get
            Set
                Me.endField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AdjustSeconds() As Integer
            Get
                Return Me.adjustSecondsField
            End Get
            Set
                Me.adjustSecondsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class Organisation
        Inherits EntityBase
        
        Private organisationNameField As String
        
        Private gMTOffsetField As Integer
        
        Private languageField As String
        
        Private activeField As Boolean
        
        Private fMWebManagedField As Boolean
        
        Private mapProviderIDField As String
        
        Private companyIDField As Integer
        
        '''<remarks/>
        Public Property OrganisationName() As String
            Get
                Return Me.organisationNameField
            End Get
            Set
                Me.organisationNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GMTOffset() As Integer
            Get
                Return Me.gMTOffsetField
            End Get
            Set
                Me.gMTOffsetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Active() As Boolean
            Get
                Return Me.activeField
            End Get
            Set
                Me.activeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FMWebManaged() As Boolean
            Get
                Return Me.fMWebManagedField
            End Get
            Set
                Me.fMWebManagedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MapProviderID() As String
            Get
                Return Me.mapProviderIDField
            End Get
            Set
                Me.mapProviderIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompanyID() As Integer
            Get
                Return Me.companyIDField
            End Get
            Set
                Me.companyIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class [Function]
        Inherits EntityBase
        
        Private moduleIDField As Integer
        
        Private nameField As String
        
        Private descriptionField As String
        
        Private extAppIDField As String
        
        '''<remarks/>
        Public Property ModuleID() As Integer
            Get
                Return Me.moduleIDField
            End Get
            Set
                Me.moduleIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtAppID() As String
            Get
                Return Me.extAppIDField
            End Get
            Set
                Me.extAppIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class UIView
        Inherits EntityBase
        
        Private nameField As String
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class User
        Inherits EntityBase
        
        Private userNameField As String
        
        Private hasAlertsField As Boolean
        
        Private hasQuickLinksField As Boolean
        
        Private displayNameField As String
        
        Private allowedToLoginField As Boolean
        
        Private defaultOrgIDField As Integer
        
        Private passwordField As String
        
        Private languageField As String
        
        Private workPhoneField As String
        
        Private workFaxField As String
        
        Private mobilePhoneField As String
        
        Private homePhoneField As String
        
        Private eMailField As String
        
        Private commentsField As String
        
        Private loginExpiresField As Boolean
        
        Private loginExpireDateField As Date
        
        Private consumptionTypeField As ConsumptionType
        
        Private measurementTypeField As MeasurementType
        
        Private fuelCaptureVolumeTypeField As MeasurementType
        
        Private fuelCaptureDistanceTypeField As MeasurementType
        
        Private gMTOffsetInSecondsField As Integer
        
        Private gMTTypeField As GMTOffsetType
        
        Private viewNameField As String
        
        Private viewIDField As String
        
        Private lCIDField As Integer
        
        Private currentOrgIDField As Integer
        
        Private gMTOffsetField As TimeSpan
        
        Private viewField As UIView
        
        '''<remarks/>
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HasAlerts() As Boolean
            Get
                Return Me.hasAlertsField
            End Get
            Set
                Me.hasAlertsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HasQuickLinks() As Boolean
            Get
                Return Me.hasQuickLinksField
            End Get
            Set
                Me.hasQuickLinksField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowedToLogin() As Boolean
            Get
                Return Me.allowedToLoginField
            End Get
            Set
                Me.allowedToLoginField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DefaultOrgID() As Integer
            Get
                Return Me.defaultOrgIDField
            End Get
            Set
                Me.defaultOrgIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WorkPhone() As String
            Get
                Return Me.workPhoneField
            End Get
            Set
                Me.workPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WorkFax() As String
            Get
                Return Me.workFaxField
            End Get
            Set
                Me.workFaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MobilePhone() As String
            Get
                Return Me.mobilePhoneField
            End Get
            Set
                Me.mobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HomePhone() As String
            Get
                Return Me.homePhoneField
            End Get
            Set
                Me.homePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EMail() As String
            Get
                Return Me.eMailField
            End Get
            Set
                Me.eMailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Comments() As String
            Get
                Return Me.commentsField
            End Get
            Set
                Me.commentsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LoginExpires() As Boolean
            Get
                Return Me.loginExpiresField
            End Get
            Set
                Me.loginExpiresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LoginExpireDate() As Date
            Get
                Return Me.loginExpireDateField
            End Get
            Set
                Me.loginExpireDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConsumptionType() As ConsumptionType
            Get
                Return Me.consumptionTypeField
            End Get
            Set
                Me.consumptionTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MeasurementType() As MeasurementType
            Get
                Return Me.measurementTypeField
            End Get
            Set
                Me.measurementTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FuelCaptureVolumeType() As MeasurementType
            Get
                Return Me.fuelCaptureVolumeTypeField
            End Get
            Set
                Me.fuelCaptureVolumeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FuelCaptureDistanceType() As MeasurementType
            Get
                Return Me.fuelCaptureDistanceTypeField
            End Get
            Set
                Me.fuelCaptureDistanceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GMTOffsetInSeconds() As Integer
            Get
                Return Me.gMTOffsetInSecondsField
            End Get
            Set
                Me.gMTOffsetInSecondsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GMTType() As GMTOffsetType
            Get
                Return Me.gMTTypeField
            End Get
            Set
                Me.gMTTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewName() As String
            Get
                Return Me.viewNameField
            End Get
            Set
                Me.viewNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewID() As String
            Get
                Return Me.viewIDField
            End Get
            Set
                Me.viewIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LCID() As Integer
            Get
                Return Me.lCIDField
            End Get
            Set
                Me.lCIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrentOrgID() As Integer
            Get
                Return Me.currentOrgIDField
            End Get
            Set
                Me.currentOrgIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GMTOffset() As TimeSpan
            Get
                Return Me.gMTOffsetField
            End Get
            Set
                Me.gMTOffsetField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property View() As UIView
            Get
                Return Me.viewField
            End Get
            Set
                Me.viewField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Public Enum ConsumptionType
        
        '''<remarks/>
        VolumeUnitsPer100DistanceUnits
        
        '''<remarks/>
        DistanceUnitsPerVolumeUnits
        
        '''<remarks/>
        DistanceUnitsPerVolumeUnits2
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Public Enum MeasurementType
        
        '''<remarks/>
        UseDefault
        
        '''<remarks/>
        Metric
        
        '''<remarks/>
        Imperial
        
        '''<remarks/>
        USImperial
        
        '''<remarks/>
        MetresPerMinute
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Public Enum GMTOffsetType
        
        '''<remarks/>
        UnSet
        
        '''<remarks/>
        OrganisazionGMT
        
        '''<remarks/>
        RegionalGMT
        
        '''<remarks/>
        DefinedGMT
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class UserContext
        
        Private loginUserField As User
        
        Private allowedOrganisationsField() As Organisation
        
        Private allowedFunctionsField() As [Function]
        
        Private currentOrganisationField As Organisation
        
        Private currentOrganisationIDField As Integer
        
        Private serverGMTOffsetField As Integer
        
        '''<remarks/>
        Public Property LoginUser() As User
            Get
                Return Me.loginUserField
            End Get
            Set
                Me.loginUserField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowedOrganisations() As Organisation()
            Get
                Return Me.allowedOrganisationsField
            End Get
            Set
                Me.allowedOrganisationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowedFunctions() As [Function]()
            Get
                Return Me.allowedFunctionsField
            End Get
            Set
                Me.allowedFunctionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrentOrganisation() As Organisation
            Get
                Return Me.currentOrganisationField
            End Get
            Set
                Me.currentOrganisationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrentOrganisationID() As Integer
            Get
                Return Me.currentOrganisationIDField
            End Get
            Set
                Me.currentOrganisationIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServerGMTOffset() As Integer
            Get
                Return Me.serverGMTOffsetField
            End Get
            Set
                Me.serverGMTOffsetField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class LoginResult
        
        Private indicatorField As Indicators
        
        Private lastLoginDateField As Date
        
        Private currentUserContextField As UserContext
        
        '''<remarks/>
        Public Property Indicator() As Indicators
            Get
                Return Me.indicatorField
            End Get
            Set
                Me.indicatorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastLoginDate() As Date
            Get
                Return Me.lastLoginDateField
            End Get
            Set
                Me.lastLoginDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CurrentUserContext() As UserContext
            Get
                Return Me.currentUserContextField
            End Get
            Set
                Me.currentUserContextField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Public Enum Indicators
        
        '''<remarks/>
        Success
        
        '''<remarks/>
        InvalidLogin
        
        '''<remarks/>
        Expired
        
        '''<remarks/>
        ChangePassword
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Core")>  _
    Partial Public Class WebLoginResult
        
        Private tokenField As String
        
        Private coreLoginResultField As LoginResult
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CoreLoginResult() As LoginResult
            Get
                Return Me.coreLoginResultField
            End Get
            Set
                Me.coreLoginResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub LoginCompletedEventHandler(ByVal sender As Object, ByVal e As LoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As WebLoginResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),WebLoginResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AdminLoginCompletedEventHandler(ByVal sender As Object, ByVal e As AdminLoginCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AdminLoginCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As WebLoginResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),WebLoginResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetUserContextCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserContextCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserContextCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As UserContext
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserContext)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetUserContext_NoMultiSearchCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserContext_NoMultiSearchCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserContext_NoMultiSearchCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As UserContext
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserContext)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub LoadDaylightSavingsSettingsCompletedEventHandler(ByVal sender As Object, ByVal e As LoadDaylightSavingsSettingsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LoadDaylightSavingsSettingsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DaylightSaving
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DaylightSaving)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub SetCurrentOrgIDCompletedEventHandler(ByVal sender As Object, ByVal e As SetCurrentOrgIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetCurrentOrgIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As UserContext
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),UserContext)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetWebServiceURLsCompletedEventHandler(ByVal sender As Object, ByVal e As GetWebServiceURLsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetWebServiceURLsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As WebServiceURL()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),WebServiceURL())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetFunctionsForUserCompletedEventHandler(ByVal sender As Object, ByVal e As GetFunctionsForUserCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetFunctionsForUserCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetUsersForOrganisationCompletedEventHandler(ByVal sender As Object, ByVal e As GetUsersForOrganisationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUsersForOrganisationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As User()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),User())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetCurrentOrgIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetCurrentOrgIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCurrentOrgIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
