<?xml version="1.0" encoding="utf-8"?><Database Name="Transport_Comp1" Class="PositonsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql1;Initial Catalog=Transport_Comp1;Persist Security Info=True;User ID=abacus" SettingsObjectName="Position_Updater.My.MySettings" SettingsPropertyName="Transport_Comp1ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vehicle" Member="Vehicles">
    <Type Name="Vehicle">
      <Column Name="dwVehicleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="szRegistration" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="bSold" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>