'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace EventDescriptionProcessWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EventDescriptionProcessWSSoap", [Namespace]:="http://www.mixtelematics.com/WebServices/UnitConfiguration"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityBase))>  _
    Partial Public Class EventDescriptionProcessWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private tokenHeaderValueField As TokenHeader
        
        Private GetEventsListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInUseEventsForVehicleIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetEventDescriptionDetailsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Position_Updater.My.MySettings.Default.Position_Updater_EventDescriptionProcessWS_EventDescriptionProcessWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property TokenHeaderValue() As TokenHeader
            Get
                Return Me.tokenHeaderValueField
            End Get
            Set
                Me.tokenHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetEventsListCompleted As GetEventsListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInUseEventsForVehicleIDCompleted As GetInUseEventsForVehicleIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetEventDescriptionDetailsCompleted As GetEventDescriptionDetailsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mixtelematics.com/WebServices/UnitConfiguration/GetEventsList", RequestNamespace:="http://www.mixtelematics.com/WebServices/UnitConfiguration", ResponseNamespace:="http://www.mixtelematics.com/WebServices/UnitConfiguration", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEventsList() As EventDescription()
            Dim results() As Object = Me.Invoke("GetEventsList", New Object(-1) {})
            Return CType(results(0),EventDescription())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEventsListAsync()
            Me.GetEventsListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEventsListAsync(ByVal userState As Object)
            If (Me.GetEventsListOperationCompleted Is Nothing) Then
                Me.GetEventsListOperationCompleted = AddressOf Me.OnGetEventsListOperationCompleted
            End If
            Me.InvokeAsync("GetEventsList", New Object(-1) {}, Me.GetEventsListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEventsListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEventsListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEventsListCompleted(Me, New GetEventsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mixtelematics.com/WebServices/UnitConfiguration/GetInUseEventsForVehic"& _ 
            "leID", RequestNamespace:="http://www.mixtelematics.com/WebServices/UnitConfiguration", ResponseNamespace:="http://www.mixtelematics.com/WebServices/UnitConfiguration", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInUseEventsForVehicleID(ByVal VehicleID As Integer) As EventDescription()
            Dim results() As Object = Me.Invoke("GetInUseEventsForVehicleID", New Object() {VehicleID})
            Return CType(results(0),EventDescription())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInUseEventsForVehicleIDAsync(ByVal VehicleID As Integer)
            Me.GetInUseEventsForVehicleIDAsync(VehicleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInUseEventsForVehicleIDAsync(ByVal VehicleID As Integer, ByVal userState As Object)
            If (Me.GetInUseEventsForVehicleIDOperationCompleted Is Nothing) Then
                Me.GetInUseEventsForVehicleIDOperationCompleted = AddressOf Me.OnGetInUseEventsForVehicleIDOperationCompleted
            End If
            Me.InvokeAsync("GetInUseEventsForVehicleID", New Object() {VehicleID}, Me.GetInUseEventsForVehicleIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInUseEventsForVehicleIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInUseEventsForVehicleIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInUseEventsForVehicleIDCompleted(Me, New GetInUseEventsForVehicleIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mixtelematics.com/WebServices/UnitConfiguration/GetEventDescriptionDet"& _ 
            "ails", RequestNamespace:="http://www.mixtelematics.com/WebServices/UnitConfiguration", ResponseNamespace:="http://www.mixtelematics.com/WebServices/UnitConfiguration", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetEventDescriptionDetails(ByVal EventID As Integer) As EventDescription
            Dim results() As Object = Me.Invoke("GetEventDescriptionDetails", New Object() {EventID})
            Return CType(results(0),EventDescription)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetEventDescriptionDetailsAsync(ByVal EventID As Integer)
            Me.GetEventDescriptionDetailsAsync(EventID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetEventDescriptionDetailsAsync(ByVal EventID As Integer, ByVal userState As Object)
            If (Me.GetEventDescriptionDetailsOperationCompleted Is Nothing) Then
                Me.GetEventDescriptionDetailsOperationCompleted = AddressOf Me.OnGetEventDescriptionDetailsOperationCompleted
            End If
            Me.InvokeAsync("GetEventDescriptionDetails", New Object() {EventID}, Me.GetEventDescriptionDetailsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetEventDescriptionDetailsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetEventDescriptionDetailsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetEventDescriptionDetailsCompleted(Me, New GetEventDescriptionDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.mixtelematics.com/WebServices/UnitConfiguration"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.mixtelematics.com/WebServices/UnitConfiguration", IsNullable:=false)>  _
    Partial Public Class TokenHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private tokenField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(EventDescription)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.mixtelematics.com/WebServices/UnitConfiguration")>  _
    Partial Public MustInherit Class EntityBase
        
        Private idField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.mixtelematics.com/WebServices/UnitConfiguration")>  _
    Partial Public Class EventDescription
        Inherits EntityBase
        
        Private descriptionField As String
        
        Private eventTypeField As Byte
        
        Private inUseField As Boolean
        
        Private startOdoField As Boolean
        
        Private startPositionField As Boolean
        
        Private endOdoField As Boolean
        
        Private endPositionField As Boolean
        
        Private recordF3CountField As Boolean
        
        Private useWarningMessageField As Boolean
        
        Private avtivePositionField As Boolean
        
        Private recordTimeField As Short
        
        Private alarmTimeField As Short
        
        Private relayTimeField As Short
        
        Private relay2TimeField As Short
        
        Private criticalTimeField As Short
        
        Private activeTimeField As Short
        
        Private activeEndTimeField As Short
        
        Private trackTimeField As Short
        
        Private trackIntervalField As Short
        
        Private alarmStateField As Byte
        
        Private relayStateField As Byte
        
        Private relay2StateField As Byte
        
        Private criticalIDField As String
        
        Private warningMessageField As String
        
        Private summaryTypeField As Byte
        
        Private summaryIDField As Short
        
        Private priorityField As Byte
        
        Private eventSaveIDField As Integer
        
        Private updatedField As Date
        
        Private notesField As String
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EventType() As Byte
            Get
                Return Me.eventTypeField
            End Get
            Set
                Me.eventTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InUse() As Boolean
            Get
                Return Me.inUseField
            End Get
            Set
                Me.inUseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartOdo() As Boolean
            Get
                Return Me.startOdoField
            End Get
            Set
                Me.startOdoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartPosition() As Boolean
            Get
                Return Me.startPositionField
            End Get
            Set
                Me.startPositionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndOdo() As Boolean
            Get
                Return Me.endOdoField
            End Get
            Set
                Me.endOdoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndPosition() As Boolean
            Get
                Return Me.endPositionField
            End Get
            Set
                Me.endPositionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecordF3Count() As Boolean
            Get
                Return Me.recordF3CountField
            End Get
            Set
                Me.recordF3CountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseWarningMessage() As Boolean
            Get
                Return Me.useWarningMessageField
            End Get
            Set
                Me.useWarningMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AvtivePosition() As Boolean
            Get
                Return Me.avtivePositionField
            End Get
            Set
                Me.avtivePositionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RecordTime() As Short
            Get
                Return Me.recordTimeField
            End Get
            Set
                Me.recordTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AlarmTime() As Short
            Get
                Return Me.alarmTimeField
            End Get
            Set
                Me.alarmTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RelayTime() As Short
            Get
                Return Me.relayTimeField
            End Get
            Set
                Me.relayTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Relay2Time() As Short
            Get
                Return Me.relay2TimeField
            End Get
            Set
                Me.relay2TimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CriticalTime() As Short
            Get
                Return Me.criticalTimeField
            End Get
            Set
                Me.criticalTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActiveTime() As Short
            Get
                Return Me.activeTimeField
            End Get
            Set
                Me.activeTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActiveEndTime() As Short
            Get
                Return Me.activeEndTimeField
            End Get
            Set
                Me.activeEndTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TrackTime() As Short
            Get
                Return Me.trackTimeField
            End Get
            Set
                Me.trackTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TrackInterval() As Short
            Get
                Return Me.trackIntervalField
            End Get
            Set
                Me.trackIntervalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AlarmState() As Byte
            Get
                Return Me.alarmStateField
            End Get
            Set
                Me.alarmStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RelayState() As Byte
            Get
                Return Me.relayStateField
            End Get
            Set
                Me.relayStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Relay2State() As Byte
            Get
                Return Me.relay2StateField
            End Get
            Set
                Me.relay2StateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CriticalID() As String
            Get
                Return Me.criticalIDField
            End Get
            Set
                Me.criticalIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WarningMessage() As String
            Get
                Return Me.warningMessageField
            End Get
            Set
                Me.warningMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SummaryType() As Byte
            Get
                Return Me.summaryTypeField
            End Get
            Set
                Me.summaryTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SummaryID() As Short
            Get
                Return Me.summaryIDField
            End Get
            Set
                Me.summaryIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Priority() As Byte
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EventSaveID() As Integer
            Get
                Return Me.eventSaveIDField
            End Get
            Set
                Me.eventSaveIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Updated() As Date
            Get
                Return Me.updatedField
            End Get
            Set
                Me.updatedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetEventsListCompletedEventHandler(ByVal sender As Object, ByVal e As GetEventsListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEventsListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EventDescription()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EventDescription())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetInUseEventsForVehicleIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetInUseEventsForVehicleIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInUseEventsForVehicleIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EventDescription()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EventDescription())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetEventDescriptionDetailsCompletedEventHandler(ByVal sender As Object, ByVal e As GetEventDescriptionDetailsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetEventDescriptionDetailsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As EventDescription
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EventDescription)
            End Get
        End Property
    End Class
End Namespace
