'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Fleetfence
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Position", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Position
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CIDField As Integer
        
        Private ModemIDField As Long
        
        Private LatField As Double
        
        Private LonField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CID() As Integer
            Get
                Return Me.CIDField
            End Get
            Set
                If (Me.CIDField.Equals(value) <> true) Then
                    Me.CIDField = value
                    Me.RaisePropertyChanged("CID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ModemID() As Long
            Get
                Return Me.ModemIDField
            End Get
            Set
                If (Me.ModemIDField.Equals(value) <> true) Then
                    Me.ModemIDField = value
                    Me.RaisePropertyChanged("ModemID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Lat() As Double
            Get
                Return Me.LatField
            End Get
            Set
                If (Me.LatField.Equals(value) <> true) Then
                    Me.LatField = value
                    Me.RaisePropertyChanged("Lat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Lon() As Double
            Get
                Return Me.LonField
            End Get
            Set
                If (Me.LonField.Equals(value) <> true) Then
                    Me.LonField = value
                    Me.RaisePropertyChanged("Lon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Time() As String
            Get
                Return Me.TimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeField, value) <> true) Then
                    Me.TimeField = value
                    Me.RaisePropertyChanged("Time")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Result", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CIDField As Integer
        
        Private ModemIDField As Long
        
        Private LatField As Double
        
        Private LonField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimeField As String
        
        Private ResultCodeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultStringField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property CID() As Integer
            Get
                Return Me.CIDField
            End Get
            Set
                If (Me.CIDField.Equals(value) <> true) Then
                    Me.CIDField = value
                    Me.RaisePropertyChanged("CID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ModemID() As Long
            Get
                Return Me.ModemIDField
            End Get
            Set
                If (Me.ModemIDField.Equals(value) <> true) Then
                    Me.ModemIDField = value
                    Me.RaisePropertyChanged("ModemID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Lat() As Double
            Get
                Return Me.LatField
            End Get
            Set
                If (Me.LatField.Equals(value) <> true) Then
                    Me.LatField = value
                    Me.RaisePropertyChanged("Lat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Lon() As Double
            Get
                Return Me.LonField
            End Get
            Set
                If (Me.LonField.Equals(value) <> true) Then
                    Me.LonField = value
                    Me.RaisePropertyChanged("Lon")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property Time() As String
            Get
                Return Me.TimeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimeField, value) <> true) Then
                    Me.TimeField = value
                    Me.RaisePropertyChanged("Time")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property ResultCode() As Integer
            Get
                Return Me.ResultCodeField
            End Get
            Set
                If (Me.ResultCodeField.Equals(value) <> true) Then
                    Me.ResultCodeField = value
                    Me.RaisePropertyChanged("ResultCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property ResultString() As String
            Get
                Return Me.ResultStringField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultStringField, value) <> true) Then
                    Me.ResultStringField = value
                    Me.RaisePropertyChanged("ResultString")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Fleetfence.PositionServiceSoap")>  _
    Public Interface PositionServiceSoap
        
        'CODEGEN: Generating message contract since element name Customer from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddPosition", ReplyAction:="*")>  _
        Function AddPosition(ByVal request As Fleetfence.AddPositionRequest) As Fleetfence.AddPositionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AddPosition", ReplyAction:="*")>  _
        Function AddPositionAsync(ByVal request As Fleetfence.AddPositionRequest) As System.Threading.Tasks.Task(Of Fleetfence.AddPositionResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddPositionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddPosition", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Fleetfence.AddPositionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Fleetfence.AddPositionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddPositionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Customer As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public User As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public positions() As Fleetfence.Position
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Customer As String, ByVal User As String, ByVal Password As String, ByVal positions() As Fleetfence.Position)
            MyBase.New
            Me.Customer = Customer
            Me.User = User
            Me.Password = Password
            Me.positions = positions
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AddPositionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddPositionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Fleetfence.AddPositionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Fleetfence.AddPositionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AddPositionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public AddPositionResult() As Fleetfence.Result
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AddPositionResult() As Fleetfence.Result)
            MyBase.New
            Me.AddPositionResult = AddPositionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PositionServiceSoapChannel
        Inherits Fleetfence.PositionServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PositionServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Fleetfence.PositionServiceSoap)
        Implements Fleetfence.PositionServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Fleetfence_PositionServiceSoap_AddPosition(ByVal request As Fleetfence.AddPositionRequest) As Fleetfence.AddPositionResponse Implements Fleetfence.PositionServiceSoap.AddPosition
            Return MyBase.Channel.AddPosition(request)
        End Function
        
        Public Function AddPosition(ByVal Customer As String, ByVal User As String, ByVal Password As String, ByVal positions() As Fleetfence.Position) As Fleetfence.Result()
            Dim inValue As Fleetfence.AddPositionRequest = New Fleetfence.AddPositionRequest()
            inValue.Body = New Fleetfence.AddPositionRequestBody()
            inValue.Body.Customer = Customer
            inValue.Body.User = User
            inValue.Body.Password = Password
            inValue.Body.positions = positions
            Dim retVal As Fleetfence.AddPositionResponse = CType(Me,Fleetfence.PositionServiceSoap).AddPosition(inValue)
            Return retVal.Body.AddPositionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Fleetfence_PositionServiceSoap_AddPositionAsync(ByVal request As Fleetfence.AddPositionRequest) As System.Threading.Tasks.Task(Of Fleetfence.AddPositionResponse) Implements Fleetfence.PositionServiceSoap.AddPositionAsync
            Return MyBase.Channel.AddPositionAsync(request)
        End Function
        
        Public Function AddPositionAsync(ByVal Customer As String, ByVal User As String, ByVal Password As String, ByVal positions() As Fleetfence.Position) As System.Threading.Tasks.Task(Of Fleetfence.AddPositionResponse)
            Dim inValue As Fleetfence.AddPositionRequest = New Fleetfence.AddPositionRequest()
            inValue.Body = New Fleetfence.AddPositionRequestBody()
            inValue.Body.Customer = Customer
            inValue.Body.User = User
            inValue.Body.Password = Password
            inValue.Body.positions = positions
            Return CType(Me,Fleetfence.PositionServiceSoap).AddPositionAsync(inValue)
        End Function
    End Class
End Namespace
