'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PositioningWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PositioningWSSoap", [Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityBase))>  _
    Partial Public Class PositioningWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private tokenHeaderValueField As TokenHeader
        
        Private GetLatest1GPSPositionForVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLatestXGPSPositionsForVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsSinceDateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsForVehicleSinceDateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsInDateRangeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsForVehicleInDateRangeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLatestPositionPerVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsInListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsSinceIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetGPSPositionsForSpecifiedVehiclesSinceIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetReverseGeoForGPSPositionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetPositionsV2SinceIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetLatestPositionV2PerVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://api.fm-web.co.uk/webservices/PositioningWebSvc/PositioningWS.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property TokenHeaderValue() As TokenHeader
            Get
                Return Me.tokenHeaderValueField
            End Get
            Set
                Me.tokenHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetLatest1GPSPositionForVehicleCompleted As GetLatest1GPSPositionForVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLatestXGPSPositionsForVehicleCompleted As GetLatestXGPSPositionsForVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsSinceDateCompleted As GetGPSPositionsSinceDateCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsForVehicleSinceDateCompleted As GetGPSPositionsForVehicleSinceDateCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsInDateRangeCompleted As GetGPSPositionsInDateRangeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsForVehicleInDateRangeCompleted As GetGPSPositionsForVehicleInDateRangeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLatestPositionPerVehicleCompleted As GetLatestPositionPerVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsInListCompleted As GetGPSPositionsInListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsSinceIDCompleted As GetGPSPositionsSinceIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetGPSPositionsForSpecifiedVehiclesSinceIDCompleted As GetGPSPositionsForSpecifiedVehiclesSinceIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetReverseGeoForGPSPositionsCompleted As GetReverseGeoForGPSPositionsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetPositionsV2SinceIDCompleted As GetPositionsV2SinceIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetLatestPositionV2PerVehicleCompleted As GetLatestPositionV2PerVehicleCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetLatest1GPSPositionForVehi"& _ 
            "cle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLatest1GPSPositionForVehicle(ByVal VehicleID As Short) As GPSPosition
            Dim results() As Object = Me.Invoke("GetLatest1GPSPositionForVehicle", New Object() {VehicleID})
            Return CType(results(0),GPSPosition)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLatest1GPSPositionForVehicleAsync(ByVal VehicleID As Short)
            Me.GetLatest1GPSPositionForVehicleAsync(VehicleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLatest1GPSPositionForVehicleAsync(ByVal VehicleID As Short, ByVal userState As Object)
            If (Me.GetLatest1GPSPositionForVehicleOperationCompleted Is Nothing) Then
                Me.GetLatest1GPSPositionForVehicleOperationCompleted = AddressOf Me.OnGetLatest1GPSPositionForVehicleOperationCompleted
            End If
            Me.InvokeAsync("GetLatest1GPSPositionForVehicle", New Object() {VehicleID}, Me.GetLatest1GPSPositionForVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLatest1GPSPositionForVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLatest1GPSPositionForVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLatest1GPSPositionForVehicleCompleted(Me, New GetLatest1GPSPositionForVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetLatestXGPSPositionsForVeh"& _ 
            "icle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLatestXGPSPositionsForVehicle(ByVal VehicleID As Short, ByVal X As Integer) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetLatestXGPSPositionsForVehicle", New Object() {VehicleID, X})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLatestXGPSPositionsForVehicleAsync(ByVal VehicleID As Short, ByVal X As Integer)
            Me.GetLatestXGPSPositionsForVehicleAsync(VehicleID, X, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLatestXGPSPositionsForVehicleAsync(ByVal VehicleID As Short, ByVal X As Integer, ByVal userState As Object)
            If (Me.GetLatestXGPSPositionsForVehicleOperationCompleted Is Nothing) Then
                Me.GetLatestXGPSPositionsForVehicleOperationCompleted = AddressOf Me.OnGetLatestXGPSPositionsForVehicleOperationCompleted
            End If
            Me.InvokeAsync("GetLatestXGPSPositionsForVehicle", New Object() {VehicleID, X}, Me.GetLatestXGPSPositionsForVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLatestXGPSPositionsForVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLatestXGPSPositionsForVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLatestXGPSPositionsForVehicleCompleted(Me, New GetLatestXGPSPositionsForVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsSinceDate", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsSinceDate(ByVal LastDate As Date) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsSinceDate", New Object() {LastDate})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsSinceDateAsync(ByVal LastDate As Date)
            Me.GetGPSPositionsSinceDateAsync(LastDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsSinceDateAsync(ByVal LastDate As Date, ByVal userState As Object)
            If (Me.GetGPSPositionsSinceDateOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsSinceDateOperationCompleted = AddressOf Me.OnGetGPSPositionsSinceDateOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsSinceDate", New Object() {LastDate}, Me.GetGPSPositionsSinceDateOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsSinceDateOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsSinceDateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsSinceDateCompleted(Me, New GetGPSPositionsSinceDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsForVehicleSin"& _ 
            "ceDate", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsForVehicleSinceDate(ByVal VehicleID As Short, ByVal LastDate As Date) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsForVehicleSinceDate", New Object() {VehicleID, LastDate})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsForVehicleSinceDateAsync(ByVal VehicleID As Short, ByVal LastDate As Date)
            Me.GetGPSPositionsForVehicleSinceDateAsync(VehicleID, LastDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsForVehicleSinceDateAsync(ByVal VehicleID As Short, ByVal LastDate As Date, ByVal userState As Object)
            If (Me.GetGPSPositionsForVehicleSinceDateOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsForVehicleSinceDateOperationCompleted = AddressOf Me.OnGetGPSPositionsForVehicleSinceDateOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsForVehicleSinceDate", New Object() {VehicleID, LastDate}, Me.GetGPSPositionsForVehicleSinceDateOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsForVehicleSinceDateOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsForVehicleSinceDateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsForVehicleSinceDateCompleted(Me, New GetGPSPositionsForVehicleSinceDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsInDateRange", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsInDateRange(ByVal StartDate As Date, ByVal EndDate As Date) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsInDateRange", New Object() {StartDate, EndDate})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsInDateRangeAsync(ByVal StartDate As Date, ByVal EndDate As Date)
            Me.GetGPSPositionsInDateRangeAsync(StartDate, EndDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsInDateRangeAsync(ByVal StartDate As Date, ByVal EndDate As Date, ByVal userState As Object)
            If (Me.GetGPSPositionsInDateRangeOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsInDateRangeOperationCompleted = AddressOf Me.OnGetGPSPositionsInDateRangeOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsInDateRange", New Object() {StartDate, EndDate}, Me.GetGPSPositionsInDateRangeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsInDateRangeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsInDateRangeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsInDateRangeCompleted(Me, New GetGPSPositionsInDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsForVehicleInD"& _ 
            "ateRange", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsForVehicleInDateRange(ByVal VehicleID As Short, ByVal StartDate As Date, ByVal EndDate As Date) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsForVehicleInDateRange", New Object() {VehicleID, StartDate, EndDate})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsForVehicleInDateRangeAsync(ByVal VehicleID As Short, ByVal StartDate As Date, ByVal EndDate As Date)
            Me.GetGPSPositionsForVehicleInDateRangeAsync(VehicleID, StartDate, EndDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsForVehicleInDateRangeAsync(ByVal VehicleID As Short, ByVal StartDate As Date, ByVal EndDate As Date, ByVal userState As Object)
            If (Me.GetGPSPositionsForVehicleInDateRangeOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsForVehicleInDateRangeOperationCompleted = AddressOf Me.OnGetGPSPositionsForVehicleInDateRangeOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsForVehicleInDateRange", New Object() {VehicleID, StartDate, EndDate}, Me.GetGPSPositionsForVehicleInDateRangeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsForVehicleInDateRangeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsForVehicleInDateRangeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsForVehicleInDateRangeCompleted(Me, New GetGPSPositionsForVehicleInDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetLatestPositionPerVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLatestPositionPerVehicle(ByVal SpecificVehicleIDs() As Short) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetLatestPositionPerVehicle", New Object() {SpecificVehicleIDs})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLatestPositionPerVehicleAsync(ByVal SpecificVehicleIDs() As Short)
            Me.GetLatestPositionPerVehicleAsync(SpecificVehicleIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLatestPositionPerVehicleAsync(ByVal SpecificVehicleIDs() As Short, ByVal userState As Object)
            If (Me.GetLatestPositionPerVehicleOperationCompleted Is Nothing) Then
                Me.GetLatestPositionPerVehicleOperationCompleted = AddressOf Me.OnGetLatestPositionPerVehicleOperationCompleted
            End If
            Me.InvokeAsync("GetLatestPositionPerVehicle", New Object() {SpecificVehicleIDs}, Me.GetLatestPositionPerVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLatestPositionPerVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLatestPositionPerVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLatestPositionPerVehicleCompleted(Me, New GetLatestPositionPerVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsInList", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsInList(ByVal SpecificGPSIDs() As Long) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsInList", New Object() {SpecificGPSIDs})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsInListAsync(ByVal SpecificGPSIDs() As Long)
            Me.GetGPSPositionsInListAsync(SpecificGPSIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsInListAsync(ByVal SpecificGPSIDs() As Long, ByVal userState As Object)
            If (Me.GetGPSPositionsInListOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsInListOperationCompleted = AddressOf Me.OnGetGPSPositionsInListOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsInList", New Object() {SpecificGPSIDs}, Me.GetGPSPositionsInListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsInListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsInListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsInListCompleted(Me, New GetGPSPositionsInListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsSinceID", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsSinceID(ByVal fromID As Long) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsSinceID", New Object() {fromID})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsSinceIDAsync(ByVal fromID As Long)
            Me.GetGPSPositionsSinceIDAsync(fromID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsSinceIDAsync(ByVal fromID As Long, ByVal userState As Object)
            If (Me.GetGPSPositionsSinceIDOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsSinceIDOperationCompleted = AddressOf Me.OnGetGPSPositionsSinceIDOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsSinceID", New Object() {fromID}, Me.GetGPSPositionsSinceIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsSinceIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsSinceIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsSinceIDCompleted(Me, New GetGPSPositionsSinceIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetGPSPositionsForSpecifiedV"& _ 
            "ehiclesSinceID", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetGPSPositionsForSpecifiedVehiclesSinceID(ByVal fromID As Long, ByVal VehicleIDs As String) As GPSPosition()
            Dim results() As Object = Me.Invoke("GetGPSPositionsForSpecifiedVehiclesSinceID", New Object() {fromID, VehicleIDs})
            Return CType(results(0),GPSPosition())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsForSpecifiedVehiclesSinceIDAsync(ByVal fromID As Long, ByVal VehicleIDs As String)
            Me.GetGPSPositionsForSpecifiedVehiclesSinceIDAsync(fromID, VehicleIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetGPSPositionsForSpecifiedVehiclesSinceIDAsync(ByVal fromID As Long, ByVal VehicleIDs As String, ByVal userState As Object)
            If (Me.GetGPSPositionsForSpecifiedVehiclesSinceIDOperationCompleted Is Nothing) Then
                Me.GetGPSPositionsForSpecifiedVehiclesSinceIDOperationCompleted = AddressOf Me.OnGetGPSPositionsForSpecifiedVehiclesSinceIDOperationCompleted
            End If
            Me.InvokeAsync("GetGPSPositionsForSpecifiedVehiclesSinceID", New Object() {fromID, VehicleIDs}, Me.GetGPSPositionsForSpecifiedVehiclesSinceIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetGPSPositionsForSpecifiedVehiclesSinceIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetGPSPositionsForSpecifiedVehiclesSinceIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetGPSPositionsForSpecifiedVehiclesSinceIDCompleted(Me, New GetGPSPositionsForSpecifiedVehiclesSinceIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetReverseGeoForGPSPositions"& _ 
            "", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetReverseGeoForGPSPositions(ByVal GPSIDs() As Long) As GeoLocation()
            Dim results() As Object = Me.Invoke("GetReverseGeoForGPSPositions", New Object() {GPSIDs})
            Return CType(results(0),GeoLocation())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetReverseGeoForGPSPositionsAsync(ByVal GPSIDs() As Long)
            Me.GetReverseGeoForGPSPositionsAsync(GPSIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetReverseGeoForGPSPositionsAsync(ByVal GPSIDs() As Long, ByVal userState As Object)
            If (Me.GetReverseGeoForGPSPositionsOperationCompleted Is Nothing) Then
                Me.GetReverseGeoForGPSPositionsOperationCompleted = AddressOf Me.OnGetReverseGeoForGPSPositionsOperationCompleted
            End If
            Me.InvokeAsync("GetReverseGeoForGPSPositions", New Object() {GPSIDs}, Me.GetReverseGeoForGPSPositionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetReverseGeoForGPSPositionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetReverseGeoForGPSPositionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetReverseGeoForGPSPositionsCompleted(Me, New GetReverseGeoForGPSPositionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetPositionsV2SinceID", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetPositionsV2SinceID(ByVal fromID As Long) As GPSPositionV2()
            Dim results() As Object = Me.Invoke("GetPositionsV2SinceID", New Object() {fromID})
            Return CType(results(0),GPSPositionV2())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetPositionsV2SinceIDAsync(ByVal fromID As Long)
            Me.GetPositionsV2SinceIDAsync(fromID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetPositionsV2SinceIDAsync(ByVal fromID As Long, ByVal userState As Object)
            If (Me.GetPositionsV2SinceIDOperationCompleted Is Nothing) Then
                Me.GetPositionsV2SinceIDOperationCompleted = AddressOf Me.OnGetPositionsV2SinceIDOperationCompleted
            End If
            Me.InvokeAsync("GetPositionsV2SinceID", New Object() {fromID}, Me.GetPositionsV2SinceIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetPositionsV2SinceIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetPositionsV2SinceIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetPositionsV2SinceIDCompleted(Me, New GetPositionsV2SinceIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/Positioning/GetLatestPositionV2PerVehicl"& _ 
            "e", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/Positioning", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetLatestPositionV2PerVehicle(ByVal SpecificVehicleIDs() As Short) As GPSPositionV2()
            Dim results() As Object = Me.Invoke("GetLatestPositionV2PerVehicle", New Object() {SpecificVehicleIDs})
            Return CType(results(0),GPSPositionV2())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetLatestPositionV2PerVehicleAsync(ByVal SpecificVehicleIDs() As Short)
            Me.GetLatestPositionV2PerVehicleAsync(SpecificVehicleIDs, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetLatestPositionV2PerVehicleAsync(ByVal SpecificVehicleIDs() As Short, ByVal userState As Object)
            If (Me.GetLatestPositionV2PerVehicleOperationCompleted Is Nothing) Then
                Me.GetLatestPositionV2PerVehicleOperationCompleted = AddressOf Me.OnGetLatestPositionV2PerVehicleOperationCompleted
            End If
            Me.InvokeAsync("GetLatestPositionV2PerVehicle", New Object() {SpecificVehicleIDs}, Me.GetLatestPositionV2PerVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetLatestPositionV2PerVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetLatestPositionV2PerVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetLatestPositionV2PerVehicleCompleted(Me, New GetLatestPositionV2PerVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning", IsNullable:=false)>  _
    Partial Public Class TokenHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private tokenField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning")>  _
    Partial Public Class GeoLocation
        
        Private roadField As String
        
        Private suburbField As String
        
        Private townField As String
        
        Private cityField As String
        
        Private zipField As String
        
        Private regionField As String
        
        Private countryField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Road() As String
            Get
                Return Me.roadField
            End Get
            Set
                Me.roadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Suburb() As String
            Get
                Return Me.suburbField
            End Get
            Set
                Me.suburbField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Town() As String
            Get
                Return Me.townField
            End Get
            Set
                Me.townField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property City() As String
            Get
                Return Me.cityField
            End Get
            Set
                Me.cityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Zip() As String
            Get
                Return Me.zipField
            End Get
            Set
                Me.zipField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Region() As String
            Get
                Return Me.regionField
            End Get
            Set
                Me.regionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(GPSPositionV2)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(GPSPosition)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning")>  _
    Partial Public MustInherit Class EntityBase
        
        Private idField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning")>  _
    Partial Public Class GPSPositionV2
        Inherits EntityBase
        
        Private vehicleIDField As Short
        
        Private driverIDField As Short
        
        Private originalDriverIDField As Short
        
        Private blockSeqField As Integer
        
        Private timeField As Date
        
        Private latitudeField As Single
        
        Private longitudeField As Single
        
        Private altitudeField As Short
        
        Private headingField As Short
        
        Private satellitesField As Byte
        
        Private hDOPField As Single
        
        Private ageOfReadingField As Integer
        
        Private distanceSinceReadingField As Integer
        
        Private velocityField As Byte
        
        Private isAVLField As Boolean
        
        Private odometerField As System.Nullable(Of Single)
        
        Private coordValidField As Boolean
        
        '''<remarks/>
        Public Property VehicleID() As Short
            Get
                Return Me.vehicleIDField
            End Get
            Set
                Me.vehicleIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DriverID() As Short
            Get
                Return Me.driverIDField
            End Get
            Set
                Me.driverIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OriginalDriverID() As Short
            Get
                Return Me.originalDriverIDField
            End Get
            Set
                Me.originalDriverIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BlockSeq() As Integer
            Get
                Return Me.blockSeqField
            End Get
            Set
                Me.blockSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Time() As Date
            Get
                Return Me.timeField
            End Get
            Set
                Me.timeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Latitude() As Single
            Get
                Return Me.latitudeField
            End Get
            Set
                Me.latitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Longitude() As Single
            Get
                Return Me.longitudeField
            End Get
            Set
                Me.longitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Altitude() As Short
            Get
                Return Me.altitudeField
            End Get
            Set
                Me.altitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Heading() As Short
            Get
                Return Me.headingField
            End Get
            Set
                Me.headingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Satellites() As Byte
            Get
                Return Me.satellitesField
            End Get
            Set
                Me.satellitesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HDOP() As Single
            Get
                Return Me.hDOPField
            End Get
            Set
                Me.hDOPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AgeOfReading() As Integer
            Get
                Return Me.ageOfReadingField
            End Get
            Set
                Me.ageOfReadingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistanceSinceReading() As Integer
            Get
                Return Me.distanceSinceReadingField
            End Get
            Set
                Me.distanceSinceReadingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Velocity() As Byte
            Get
                Return Me.velocityField
            End Get
            Set
                Me.velocityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAVL() As Boolean
            Get
                Return Me.isAVLField
            End Get
            Set
                Me.isAVLField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Odometer() As System.Nullable(Of Single)
            Get
                Return Me.odometerField
            End Get
            Set
                Me.odometerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CoordValid() As Boolean
            Get
                Return Me.coordValidField
            End Get
            Set
                Me.coordValidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/Positioning")>  _
    Partial Public Class GPSPosition
        Inherits EntityBase
        
        Private vehicleIDField As Short
        
        Private driverIDField As Short
        
        Private originalDriverIDField As Short
        
        Private blockSeqField As Integer
        
        Private timeField As Date
        
        Private latitudeField As Single
        
        Private longitudeField As Single
        
        Private altitudeField As Short
        
        Private headingField As Short
        
        Private satellitesField As Byte
        
        Private hDOPField As Single
        
        Private ageOfReadingField As Integer
        
        Private distanceSinceReadingField As Integer
        
        Private velocityField As Byte
        
        Private isAVLField As Boolean
        
        Private coordValidField As Boolean
        
        '''<remarks/>
        Public Property VehicleID() As Short
            Get
                Return Me.vehicleIDField
            End Get
            Set
                Me.vehicleIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DriverID() As Short
            Get
                Return Me.driverIDField
            End Get
            Set
                Me.driverIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OriginalDriverID() As Short
            Get
                Return Me.originalDriverIDField
            End Get
            Set
                Me.originalDriverIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BlockSeq() As Integer
            Get
                Return Me.blockSeqField
            End Get
            Set
                Me.blockSeqField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Time() As Date
            Get
                Return Me.timeField
            End Get
            Set
                Me.timeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Latitude() As Single
            Get
                Return Me.latitudeField
            End Get
            Set
                Me.latitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Longitude() As Single
            Get
                Return Me.longitudeField
            End Get
            Set
                Me.longitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Altitude() As Short
            Get
                Return Me.altitudeField
            End Get
            Set
                Me.altitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Heading() As Short
            Get
                Return Me.headingField
            End Get
            Set
                Me.headingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Satellites() As Byte
            Get
                Return Me.satellitesField
            End Get
            Set
                Me.satellitesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HDOP() As Single
            Get
                Return Me.hDOPField
            End Get
            Set
                Me.hDOPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AgeOfReading() As Integer
            Get
                Return Me.ageOfReadingField
            End Get
            Set
                Me.ageOfReadingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistanceSinceReading() As Integer
            Get
                Return Me.distanceSinceReadingField
            End Get
            Set
                Me.distanceSinceReadingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Velocity() As Byte
            Get
                Return Me.velocityField
            End Get
            Set
                Me.velocityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAVL() As Boolean
            Get
                Return Me.isAVLField
            End Get
            Set
                Me.isAVLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CoordValid() As Boolean
            Get
                Return Me.coordValidField
            End Get
            Set
                Me.coordValidField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetLatest1GPSPositionForVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As GetLatest1GPSPositionForVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLatest1GPSPositionForVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetLatestXGPSPositionsForVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As GetLatestXGPSPositionsForVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLatestXGPSPositionsForVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsSinceDateCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsSinceDateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsSinceDateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsForVehicleSinceDateCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsForVehicleSinceDateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsForVehicleSinceDateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsInDateRangeCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsInDateRangeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsInDateRangeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsForVehicleInDateRangeCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsForVehicleInDateRangeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsForVehicleInDateRangeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetLatestPositionPerVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As GetLatestPositionPerVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLatestPositionPerVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsInListCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsInListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsInListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsSinceIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsSinceIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsSinceIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetGPSPositionsForSpecifiedVehiclesSinceIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetGPSPositionsForSpecifiedVehiclesSinceIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetGPSPositionsForSpecifiedVehiclesSinceIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPosition()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPosition())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetReverseGeoForGPSPositionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetReverseGeoForGPSPositionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetReverseGeoForGPSPositionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GeoLocation()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GeoLocation())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetPositionsV2SinceIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetPositionsV2SinceIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetPositionsV2SinceIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPositionV2()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPositionV2())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetLatestPositionV2PerVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As GetLatestPositionV2PerVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetLatestPositionV2PerVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As GPSPositionV2()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),GPSPositionV2())
            End Get
        End Property
    End Class
End Namespace
