'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace DriverProcessesWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DriverProcessesWSSoap", [Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityBase))>  _
    Partial Public Class DriverProcessesWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private tokenHeaderValueField As TokenHeader
        
        Private AddBasicDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDriverListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDriverListFilteredOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDriverScoresInDateRangeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDriverReportingGroupListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDriverReportingGroupOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportingGroupAddDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportingGroupRemoveDriverOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Position_Updater.My.MySettings.Default.Position_Updater_DriverProcessesWS_DriverProcessesWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property TokenHeaderValue() As TokenHeader
            Get
                Return Me.tokenHeaderValueField
            End Get
            Set
                Me.tokenHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AddBasicDriverCompleted As AddBasicDriverCompletedEventHandler
        
        '''<remarks/>
        Public Event AddDriverCompleted As AddDriverCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateDriverCompleted As UpdateDriverCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteDriverCompleted As DeleteDriverCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDriverCompleted As GetDriverCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDriverListCompleted As GetDriverListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDriverListFilteredCompleted As GetDriverListFilteredCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDriverScoresInDateRangeCompleted As GetDriverScoresInDateRangeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDriverReportingGroupListCompleted As GetDriverReportingGroupListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDriverReportingGroupCompleted As GetDriverReportingGroupCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportingGroupAddDriverCompleted As ReportingGroupAddDriverCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportingGroupRemoveDriverCompleted As ReportingGroupRemoveDriverCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/AddBasicDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddBasicDriver(ByVal DriverID As Short, ByVal EmployeeNumber As String, ByVal Name As String, ByVal SiteID As Integer, ByVal GroupID As Integer) As Short
            Dim results() As Object = Me.Invoke("AddBasicDriver", New Object() {DriverID, EmployeeNumber, Name, SiteID, GroupID})
            Return CType(results(0),Short)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddBasicDriverAsync(ByVal DriverID As Short, ByVal EmployeeNumber As String, ByVal Name As String, ByVal SiteID As Integer, ByVal GroupID As Integer)
            Me.AddBasicDriverAsync(DriverID, EmployeeNumber, Name, SiteID, GroupID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddBasicDriverAsync(ByVal DriverID As Short, ByVal EmployeeNumber As String, ByVal Name As String, ByVal SiteID As Integer, ByVal GroupID As Integer, ByVal userState As Object)
            If (Me.AddBasicDriverOperationCompleted Is Nothing) Then
                Me.AddBasicDriverOperationCompleted = AddressOf Me.OnAddBasicDriverOperationCompleted
            End If
            Me.InvokeAsync("AddBasicDriver", New Object() {DriverID, EmployeeNumber, Name, SiteID, GroupID}, Me.AddBasicDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddBasicDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddBasicDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddBasicDriverCompleted(Me, New AddBasicDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/AddDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddDriver(ByVal Driver As Driver) As Short
            Dim results() As Object = Me.Invoke("AddDriver", New Object() {Driver})
            Return CType(results(0),Short)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddDriverAsync(ByVal Driver As Driver)
            Me.AddDriverAsync(Driver, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddDriverAsync(ByVal Driver As Driver, ByVal userState As Object)
            If (Me.AddDriverOperationCompleted Is Nothing) Then
                Me.AddDriverOperationCompleted = AddressOf Me.OnAddDriverOperationCompleted
            End If
            Me.InvokeAsync("AddDriver", New Object() {Driver}, Me.AddDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddDriverCompleted(Me, New AddDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/UpdateDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateDriver(ByVal Driver As Driver) As Boolean
            Dim results() As Object = Me.Invoke("UpdateDriver", New Object() {Driver})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateDriverAsync(ByVal Driver As Driver)
            Me.UpdateDriverAsync(Driver, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateDriverAsync(ByVal Driver As Driver, ByVal userState As Object)
            If (Me.UpdateDriverOperationCompleted Is Nothing) Then
                Me.UpdateDriverOperationCompleted = AddressOf Me.OnUpdateDriverOperationCompleted
            End If
            Me.InvokeAsync("UpdateDriver", New Object() {Driver}, Me.UpdateDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateDriverCompleted(Me, New UpdateDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/DeleteDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteDriver(ByVal DriverID As Short) As Boolean
            Dim results() As Object = Me.Invoke("DeleteDriver", New Object() {DriverID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteDriverAsync(ByVal DriverID As Short)
            Me.DeleteDriverAsync(DriverID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteDriverAsync(ByVal DriverID As Short, ByVal userState As Object)
            If (Me.DeleteDriverOperationCompleted Is Nothing) Then
                Me.DeleteDriverOperationCompleted = AddressOf Me.OnDeleteDriverOperationCompleted
            End If
            Me.InvokeAsync("DeleteDriver", New Object() {DriverID}, Me.DeleteDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteDriverCompleted(Me, New DeleteDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDriver(ByVal DriverID As Short) As Driver
            Dim results() As Object = Me.Invoke("GetDriver", New Object() {DriverID})
            Return CType(results(0),Driver)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDriverAsync(ByVal DriverID As Short)
            Me.GetDriverAsync(DriverID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDriverAsync(ByVal DriverID As Short, ByVal userState As Object)
            If (Me.GetDriverOperationCompleted Is Nothing) Then
                Me.GetDriverOperationCompleted = AddressOf Me.OnGetDriverOperationCompleted
            End If
            Me.InvokeAsync("GetDriver", New Object() {DriverID}, Me.GetDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDriverCompleted(Me, New GetDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetDriverList", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDriverList() As Driver()
            Dim results() As Object = Me.Invoke("GetDriverList", New Object(-1) {})
            Return CType(results(0),Driver())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDriverListAsync()
            Me.GetDriverListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDriverListAsync(ByVal userState As Object)
            If (Me.GetDriverListOperationCompleted Is Nothing) Then
                Me.GetDriverListOperationCompleted = AddressOf Me.OnGetDriverListOperationCompleted
            End If
            Me.InvokeAsync("GetDriverList", New Object(-1) {}, Me.GetDriverListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDriverListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDriverListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDriverListCompleted(Me, New GetDriverListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetDriverListFiltered", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDriverListFiltered(ByVal searchOption As DriverSearchOption, ByVal searchText As String, ByVal firstRowNumber As Integer) As Driver()
            Dim results() As Object = Me.Invoke("GetDriverListFiltered", New Object() {searchOption, searchText, firstRowNumber})
            Return CType(results(0),Driver())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDriverListFilteredAsync(ByVal searchOption As DriverSearchOption, ByVal searchText As String, ByVal firstRowNumber As Integer)
            Me.GetDriverListFilteredAsync(searchOption, searchText, firstRowNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDriverListFilteredAsync(ByVal searchOption As DriverSearchOption, ByVal searchText As String, ByVal firstRowNumber As Integer, ByVal userState As Object)
            If (Me.GetDriverListFilteredOperationCompleted Is Nothing) Then
                Me.GetDriverListFilteredOperationCompleted = AddressOf Me.OnGetDriverListFilteredOperationCompleted
            End If
            Me.InvokeAsync("GetDriverListFiltered", New Object() {searchOption, searchText, firstRowNumber}, Me.GetDriverListFilteredOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDriverListFilteredOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDriverListFilteredCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDriverListFilteredCompleted(Me, New GetDriverListFilteredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetDriverScoresInDateRange", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDriverScoresInDateRange(ByVal DriverIDs As String, ByVal FromDate As Date, ByVal ToDate As Date) As DriverScore()
            Dim results() As Object = Me.Invoke("GetDriverScoresInDateRange", New Object() {DriverIDs, FromDate, ToDate})
            Return CType(results(0),DriverScore())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDriverScoresInDateRangeAsync(ByVal DriverIDs As String, ByVal FromDate As Date, ByVal ToDate As Date)
            Me.GetDriverScoresInDateRangeAsync(DriverIDs, FromDate, ToDate, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDriverScoresInDateRangeAsync(ByVal DriverIDs As String, ByVal FromDate As Date, ByVal ToDate As Date, ByVal userState As Object)
            If (Me.GetDriverScoresInDateRangeOperationCompleted Is Nothing) Then
                Me.GetDriverScoresInDateRangeOperationCompleted = AddressOf Me.OnGetDriverScoresInDateRangeOperationCompleted
            End If
            Me.InvokeAsync("GetDriverScoresInDateRange", New Object() {DriverIDs, FromDate, ToDate}, Me.GetDriverScoresInDateRangeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDriverScoresInDateRangeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDriverScoresInDateRangeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDriverScoresInDateRangeCompleted(Me, New GetDriverScoresInDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetDriverReportingGroupList", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDriverReportingGroupList() As DriverReportingGroup()
            Dim results() As Object = Me.Invoke("GetDriverReportingGroupList", New Object(-1) {})
            Return CType(results(0),DriverReportingGroup())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDriverReportingGroupListAsync()
            Me.GetDriverReportingGroupListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDriverReportingGroupListAsync(ByVal userState As Object)
            If (Me.GetDriverReportingGroupListOperationCompleted Is Nothing) Then
                Me.GetDriverReportingGroupListOperationCompleted = AddressOf Me.OnGetDriverReportingGroupListOperationCompleted
            End If
            Me.InvokeAsync("GetDriverReportingGroupList", New Object(-1) {}, Me.GetDriverReportingGroupListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDriverReportingGroupListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDriverReportingGroupListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDriverReportingGroupListCompleted(Me, New GetDriverReportingGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetDriverReportingGroup", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDriverReportingGroup(ByVal GroupID As Integer) As DriverReportingGroup
            Dim results() As Object = Me.Invoke("GetDriverReportingGroup", New Object() {GroupID})
            Return CType(results(0),DriverReportingGroup)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDriverReportingGroupAsync(ByVal GroupID As Integer)
            Me.GetDriverReportingGroupAsync(GroupID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDriverReportingGroupAsync(ByVal GroupID As Integer, ByVal userState As Object)
            If (Me.GetDriverReportingGroupOperationCompleted Is Nothing) Then
                Me.GetDriverReportingGroupOperationCompleted = AddressOf Me.OnGetDriverReportingGroupOperationCompleted
            End If
            Me.InvokeAsync("GetDriverReportingGroup", New Object() {GroupID}, Me.GetDriverReportingGroupOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDriverReportingGroupOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDriverReportingGroupCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDriverReportingGroupCompleted(Me, New GetDriverReportingGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/ReportingGroupAddDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportingGroupAddDriver(ByVal GroupID As Integer, ByVal DriverID As Short) As Boolean
            Dim results() As Object = Me.Invoke("ReportingGroupAddDriver", New Object() {GroupID, DriverID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupAddDriverAsync(ByVal GroupID As Integer, ByVal DriverID As Short)
            Me.ReportingGroupAddDriverAsync(GroupID, DriverID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupAddDriverAsync(ByVal GroupID As Integer, ByVal DriverID As Short, ByVal userState As Object)
            If (Me.ReportingGroupAddDriverOperationCompleted Is Nothing) Then
                Me.ReportingGroupAddDriverOperationCompleted = AddressOf Me.OnReportingGroupAddDriverOperationCompleted
            End If
            Me.InvokeAsync("ReportingGroupAddDriver", New Object() {GroupID, DriverID}, Me.ReportingGroupAddDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportingGroupAddDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportingGroupAddDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportingGroupAddDriverCompleted(Me, New ReportingGroupAddDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/ReportingGroupRemoveDriver", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportingGroupRemoveDriver(ByVal GroupID As Integer, ByVal DriverID As Short) As Boolean
            Dim results() As Object = Me.Invoke("ReportingGroupRemoveDriver", New Object() {GroupID, DriverID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupRemoveDriverAsync(ByVal GroupID As Integer, ByVal DriverID As Short)
            Me.ReportingGroupRemoveDriverAsync(GroupID, DriverID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupRemoveDriverAsync(ByVal GroupID As Integer, ByVal DriverID As Short, ByVal userState As Object)
            If (Me.ReportingGroupRemoveDriverOperationCompleted Is Nothing) Then
                Me.ReportingGroupRemoveDriverOperationCompleted = AddressOf Me.OnReportingGroupRemoveDriverOperationCompleted
            End If
            Me.InvokeAsync("ReportingGroupRemoveDriver", New Object() {GroupID, DriverID}, Me.ReportingGroupRemoveDriverOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportingGroupRemoveDriverOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportingGroupRemoveDriverCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportingGroupRemoveDriverCompleted(Me, New ReportingGroupRemoveDriverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData", IsNullable:=false)>  _
    Partial Public Class TokenHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private tokenField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class ReportingGroupMember
        
        Private idField As Short
        
        Private displayNameField As String
        
        Private siteField As String
        
        '''<remarks/>
        Public Property ID() As Short
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Site() As String
            Get
                Return Me.siteField
            End Get
            Set
                Me.siteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class DriverReportingGroup
        
        Private driversField() As ReportingGroupMember
        
        Private groupIDField As Integer
        
        Private nameField As String
        
        Private notesField As String
        
        '''<remarks/>
        Public Property Drivers() As ReportingGroupMember()
            Get
                Return Me.driversField
            End Get
            Set
                Me.driversField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroupID() As Integer
            Get
                Return Me.groupIDField
            End Get
            Set
                Me.groupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class DriverScore
        
        Private driverIDField As Short
        
        Private overallScoreField As System.Nullable(Of Single)
        
        Private distanceField As System.Nullable(Of Single)
        
        Private durationField As System.Nullable(Of Integer)
        
        Private overSpeedingScoreField As System.Nullable(Of Single)
        
        Private overRevvingScoreField As System.Nullable(Of Single)
        
        Private harshBrakingScoreField As System.Nullable(Of Single)
        
        Private outOfGreenBandDrivingScoreField As System.Nullable(Of Single)
        
        Private excessiveIdlingScoreField As System.Nullable(Of Single)
        
        Private harshAccelerationScoreField As System.Nullable(Of Single)
        
        '''<remarks/>
        Public Property DriverID() As Short
            Get
                Return Me.driverIDField
            End Get
            Set
                Me.driverIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OverallScore() As System.Nullable(Of Single)
            Get
                Return Me.overallScoreField
            End Get
            Set
                Me.overallScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Distance() As System.Nullable(Of Single)
            Get
                Return Me.distanceField
            End Get
            Set
                Me.distanceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Duration() As System.Nullable(Of Integer)
            Get
                Return Me.durationField
            End Get
            Set
                Me.durationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OverSpeedingScore() As System.Nullable(Of Single)
            Get
                Return Me.overSpeedingScoreField
            End Get
            Set
                Me.overSpeedingScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OverRevvingScore() As System.Nullable(Of Single)
            Get
                Return Me.overRevvingScoreField
            End Get
            Set
                Me.overRevvingScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property HarshBrakingScore() As System.Nullable(Of Single)
            Get
                Return Me.harshBrakingScoreField
            End Get
            Set
                Me.harshBrakingScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OutOfGreenBandDrivingScore() As System.Nullable(Of Single)
            Get
                Return Me.outOfGreenBandDrivingScoreField
            End Get
            Set
                Me.outOfGreenBandDrivingScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ExcessiveIdlingScore() As System.Nullable(Of Single)
            Get
                Return Me.excessiveIdlingScoreField
            End Get
            Set
                Me.excessiveIdlingScoreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property HarshAccelerationScore() As System.Nullable(Of Single)
            Get
                Return Me.harshAccelerationScoreField
            End Get
            Set
                Me.harshAccelerationScoreField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Driver)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public MustInherit Class EntityBase
        
        Private idField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class Driver
        Inherits EntityBase
        
        Private siteIDField As Integer
        
        Private groupIDField As Integer
        
        Private employeeNumberField As String
        
        Private extendedIDField As String
        
        Private nameField As String
        
        Private defaultAllowVehicleAccessField As Boolean
        
        Private licenseField As Boolean
        
        Private lastLicenseField As Date
        
        Private nextLicenseField As Date
        
        Private licenseIntervalField As Byte
        
        Private licenseRemindField As Byte
        
        Private licenseRemind2Field As Byte
        
        Private distanceCheckedField As Date
        
        Private createdField As Date
        
        Private updatedField As Date
        
        '''<remarks/>
        Public Property SiteID() As Integer
            Get
                Return Me.siteIDField
            End Get
            Set
                Me.siteIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroupID() As Integer
            Get
                Return Me.groupIDField
            End Get
            Set
                Me.groupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeNumber() As String
            Get
                Return Me.employeeNumberField
            End Get
            Set
                Me.employeeNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtendedID() As String
            Get
                Return Me.extendedIDField
            End Get
            Set
                Me.extendedIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DefaultAllowVehicleAccess() As Boolean
            Get
                Return Me.defaultAllowVehicleAccessField
            End Get
            Set
                Me.defaultAllowVehicleAccessField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property License() As Boolean
            Get
                Return Me.licenseField
            End Get
            Set
                Me.licenseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastLicense() As Date
            Get
                Return Me.lastLicenseField
            End Get
            Set
                Me.lastLicenseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NextLicense() As Date
            Get
                Return Me.nextLicenseField
            End Get
            Set
                Me.nextLicenseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LicenseInterval() As Byte
            Get
                Return Me.licenseIntervalField
            End Get
            Set
                Me.licenseIntervalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LicenseRemind() As Byte
            Get
                Return Me.licenseRemindField
            End Get
            Set
                Me.licenseRemindField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LicenseRemind2() As Byte
            Get
                Return Me.licenseRemind2Field
            End Get
            Set
                Me.licenseRemind2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistanceChecked() As Date
            Get
                Return Me.distanceCheckedField
            End Get
            Set
                Me.distanceCheckedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Created() As Date
            Get
                Return Me.createdField
            End Get
            Set
                Me.createdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Updated() As Date
            Get
                Return Me.updatedField
            End Get
            Set
                Me.updatedField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Public Enum DriverSearchOption
        
        '''<remarks/>
        DriverId
        
        '''<remarks/>
        EmployeeNumber
        
        '''<remarks/>
        Name
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AddBasicDriverCompletedEventHandler(ByVal sender As Object, ByVal e As AddBasicDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddBasicDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Short
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Short)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AddDriverCompletedEventHandler(ByVal sender As Object, ByVal e As AddDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Short
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Short)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub UpdateDriverCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub DeleteDriverCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetDriverCompletedEventHandler(ByVal sender As Object, ByVal e As GetDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Driver
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Driver)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetDriverListCompletedEventHandler(ByVal sender As Object, ByVal e As GetDriverListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDriverListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Driver()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Driver())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetDriverListFilteredCompletedEventHandler(ByVal sender As Object, ByVal e As GetDriverListFilteredCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDriverListFilteredCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Driver()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Driver())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetDriverScoresInDateRangeCompletedEventHandler(ByVal sender As Object, ByVal e As GetDriverScoresInDateRangeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDriverScoresInDateRangeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DriverScore()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DriverScore())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetDriverReportingGroupListCompletedEventHandler(ByVal sender As Object, ByVal e As GetDriverReportingGroupListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDriverReportingGroupListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DriverReportingGroup()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DriverReportingGroup())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetDriverReportingGroupCompletedEventHandler(ByVal sender As Object, ByVal e As GetDriverReportingGroupCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDriverReportingGroupCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DriverReportingGroup
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DriverReportingGroup)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReportingGroupAddDriverCompletedEventHandler(ByVal sender As Object, ByVal e As ReportingGroupAddDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportingGroupAddDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReportingGroupRemoveDriverCompletedEventHandler(ByVal sender As Object, ByVal e As ReportingGroupRemoveDriverCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportingGroupRemoveDriverCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
