'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace VehicleProcessesWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="VehicleProcessesWSSoap", [Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EntityBase))>  _
    Partial Public Class VehicleProcessesWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private tokenHeaderValueField As TokenHeader
        
        Private AddBasicVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateVehicleActiveStateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVehiclesListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVehiclesListFilteredOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVehiclesListByDevicePropertyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVehicleReportingGroupListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetVehicleReportingGroupOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportingGroupAddVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportingGroupRemoveVehicleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Position_Updater.My.MySettings.Default.Position_Updater_VehicleProcessesWS_VehicleProcessesWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property TokenHeaderValue() As TokenHeader
            Get
                Return Me.tokenHeaderValueField
            End Get
            Set
                Me.tokenHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AddBasicVehicleCompleted As AddBasicVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event AddVehicleCompleted As AddVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateVehicleCompleted As UpdateVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateVehicleActiveStateCompleted As UpdateVehicleActiveStateCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteVehicleCompleted As DeleteVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVehicleCompleted As GetVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVehiclesListCompleted As GetVehiclesListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVehiclesListFilteredCompleted As GetVehiclesListFilteredCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVehiclesListByDevicePropertyCompleted As GetVehiclesListByDevicePropertyCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVehicleReportingGroupListCompleted As GetVehicleReportingGroupListCompletedEventHandler
        
        '''<remarks/>
        Public Event GetVehicleReportingGroupCompleted As GetVehicleReportingGroupCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportingGroupAddVehicleCompleted As ReportingGroupAddVehicleCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportingGroupRemoveVehicleCompleted As ReportingGroupRemoveVehicleCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/AddBasicVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddBasicVehicle(ByVal VehicleID As Short, ByVal Description As String, ByVal RegistrationNumber As String, ByVal UnitType As UnitTypes, ByVal SiteID As Integer, ByVal GroupID As Integer, ByVal TargetFuelConsumption As Single, ByVal DefaultDriverID As Short) As Short
            Dim results() As Object = Me.Invoke("AddBasicVehicle", New Object() {VehicleID, Description, RegistrationNumber, UnitType, SiteID, GroupID, TargetFuelConsumption, DefaultDriverID})
            Return CType(results(0),Short)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddBasicVehicleAsync(ByVal VehicleID As Short, ByVal Description As String, ByVal RegistrationNumber As String, ByVal UnitType As UnitTypes, ByVal SiteID As Integer, ByVal GroupID As Integer, ByVal TargetFuelConsumption As Single, ByVal DefaultDriverID As Short)
            Me.AddBasicVehicleAsync(VehicleID, Description, RegistrationNumber, UnitType, SiteID, GroupID, TargetFuelConsumption, DefaultDriverID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddBasicVehicleAsync(ByVal VehicleID As Short, ByVal Description As String, ByVal RegistrationNumber As String, ByVal UnitType As UnitTypes, ByVal SiteID As Integer, ByVal GroupID As Integer, ByVal TargetFuelConsumption As Single, ByVal DefaultDriverID As Short, ByVal userState As Object)
            If (Me.AddBasicVehicleOperationCompleted Is Nothing) Then
                Me.AddBasicVehicleOperationCompleted = AddressOf Me.OnAddBasicVehicleOperationCompleted
            End If
            Me.InvokeAsync("AddBasicVehicle", New Object() {VehicleID, Description, RegistrationNumber, UnitType, SiteID, GroupID, TargetFuelConsumption, DefaultDriverID}, Me.AddBasicVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddBasicVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddBasicVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddBasicVehicleCompleted(Me, New AddBasicVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/AddVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddVehicle(ByVal Vehicle As Vehicle) As Short
            Dim results() As Object = Me.Invoke("AddVehicle", New Object() {Vehicle})
            Return CType(results(0),Short)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddVehicleAsync(ByVal Vehicle As Vehicle)
            Me.AddVehicleAsync(Vehicle, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddVehicleAsync(ByVal Vehicle As Vehicle, ByVal userState As Object)
            If (Me.AddVehicleOperationCompleted Is Nothing) Then
                Me.AddVehicleOperationCompleted = AddressOf Me.OnAddVehicleOperationCompleted
            End If
            Me.InvokeAsync("AddVehicle", New Object() {Vehicle}, Me.AddVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddVehicleCompleted(Me, New AddVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/UpdateVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateVehicle(ByVal Vehicle As Vehicle) As Boolean
            Dim results() As Object = Me.Invoke("UpdateVehicle", New Object() {Vehicle})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateVehicleAsync(ByVal Vehicle As Vehicle)
            Me.UpdateVehicleAsync(Vehicle, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateVehicleAsync(ByVal Vehicle As Vehicle, ByVal userState As Object)
            If (Me.UpdateVehicleOperationCompleted Is Nothing) Then
                Me.UpdateVehicleOperationCompleted = AddressOf Me.OnUpdateVehicleOperationCompleted
            End If
            Me.InvokeAsync("UpdateVehicle", New Object() {Vehicle}, Me.UpdateVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateVehicleCompleted(Me, New UpdateVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/UpdateVehicleActiveState", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateVehicleActiveState(ByVal VehicleID As Short, ByVal ActiveState As VehicleActiveState) As Boolean
            Dim results() As Object = Me.Invoke("UpdateVehicleActiveState", New Object() {VehicleID, ActiveState})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UpdateVehicleActiveStateAsync(ByVal VehicleID As Short, ByVal ActiveState As VehicleActiveState)
            Me.UpdateVehicleActiveStateAsync(VehicleID, ActiveState, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateVehicleActiveStateAsync(ByVal VehicleID As Short, ByVal ActiveState As VehicleActiveState, ByVal userState As Object)
            If (Me.UpdateVehicleActiveStateOperationCompleted Is Nothing) Then
                Me.UpdateVehicleActiveStateOperationCompleted = AddressOf Me.OnUpdateVehicleActiveStateOperationCompleted
            End If
            Me.InvokeAsync("UpdateVehicleActiveState", New Object() {VehicleID, ActiveState}, Me.UpdateVehicleActiveStateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateVehicleActiveStateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateVehicleActiveStateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateVehicleActiveStateCompleted(Me, New UpdateVehicleActiveStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/DeleteVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteVehicle(ByVal VehicleID As Short) As Boolean
            Dim results() As Object = Me.Invoke("DeleteVehicle", New Object() {VehicleID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteVehicleAsync(ByVal VehicleID As Short)
            Me.DeleteVehicleAsync(VehicleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteVehicleAsync(ByVal VehicleID As Short, ByVal userState As Object)
            If (Me.DeleteVehicleOperationCompleted Is Nothing) Then
                Me.DeleteVehicleOperationCompleted = AddressOf Me.OnDeleteVehicleOperationCompleted
            End If
            Me.InvokeAsync("DeleteVehicle", New Object() {VehicleID}, Me.DeleteVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteVehicleCompleted(Me, New DeleteVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVehicle(ByVal VehicleID As Short) As Vehicle
            Dim results() As Object = Me.Invoke("GetVehicle", New Object() {VehicleID})
            Return CType(results(0),Vehicle)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVehicleAsync(ByVal VehicleID As Short)
            Me.GetVehicleAsync(VehicleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVehicleAsync(ByVal VehicleID As Short, ByVal userState As Object)
            If (Me.GetVehicleOperationCompleted Is Nothing) Then
                Me.GetVehicleOperationCompleted = AddressOf Me.OnGetVehicleOperationCompleted
            End If
            Me.InvokeAsync("GetVehicle", New Object() {VehicleID}, Me.GetVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVehicleCompleted(Me, New GetVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetVehiclesList", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVehiclesList() As Vehicle()
            Dim results() As Object = Me.Invoke("GetVehiclesList", New Object(-1) {})
            Return CType(results(0),Vehicle())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVehiclesListAsync()
            Me.GetVehiclesListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVehiclesListAsync(ByVal userState As Object)
            If (Me.GetVehiclesListOperationCompleted Is Nothing) Then
                Me.GetVehiclesListOperationCompleted = AddressOf Me.OnGetVehiclesListOperationCompleted
            End If
            Me.InvokeAsync("GetVehiclesList", New Object(-1) {}, Me.GetVehiclesListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVehiclesListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVehiclesListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVehiclesListCompleted(Me, New GetVehiclesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetVehiclesListFiltered", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVehiclesListFiltered(ByVal searchOption As VehicleSearchOption, ByVal searchText As String, ByVal firstRowNumber As Integer) As Vehicle()
            Dim results() As Object = Me.Invoke("GetVehiclesListFiltered", New Object() {searchOption, searchText, firstRowNumber})
            Return CType(results(0),Vehicle())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVehiclesListFilteredAsync(ByVal searchOption As VehicleSearchOption, ByVal searchText As String, ByVal firstRowNumber As Integer)
            Me.GetVehiclesListFilteredAsync(searchOption, searchText, firstRowNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVehiclesListFilteredAsync(ByVal searchOption As VehicleSearchOption, ByVal searchText As String, ByVal firstRowNumber As Integer, ByVal userState As Object)
            If (Me.GetVehiclesListFilteredOperationCompleted Is Nothing) Then
                Me.GetVehiclesListFilteredOperationCompleted = AddressOf Me.OnGetVehiclesListFilteredOperationCompleted
            End If
            Me.InvokeAsync("GetVehiclesListFiltered", New Object() {searchOption, searchText, firstRowNumber}, Me.GetVehiclesListFilteredOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVehiclesListFilteredOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVehiclesListFilteredCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVehiclesListFilteredCompleted(Me, New GetVehiclesListFilteredCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetVehiclesListByDevicePropert"& _ 
            "y", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVehiclesListByDeviceProperty(ByVal DeviceID As Integer, ByVal [Property] As String, ByVal Value As String) As Vehicle()
            Dim results() As Object = Me.Invoke("GetVehiclesListByDeviceProperty", New Object() {DeviceID, [Property], Value})
            Return CType(results(0),Vehicle())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVehiclesListByDevicePropertyAsync(ByVal DeviceID As Integer, ByVal [Property] As String, ByVal Value As String)
            Me.GetVehiclesListByDevicePropertyAsync(DeviceID, [Property], Value, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVehiclesListByDevicePropertyAsync(ByVal DeviceID As Integer, ByVal [Property] As String, ByVal Value As String, ByVal userState As Object)
            If (Me.GetVehiclesListByDevicePropertyOperationCompleted Is Nothing) Then
                Me.GetVehiclesListByDevicePropertyOperationCompleted = AddressOf Me.OnGetVehiclesListByDevicePropertyOperationCompleted
            End If
            Me.InvokeAsync("GetVehiclesListByDeviceProperty", New Object() {DeviceID, [Property], Value}, Me.GetVehiclesListByDevicePropertyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVehiclesListByDevicePropertyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVehiclesListByDevicePropertyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVehiclesListByDevicePropertyCompleted(Me, New GetVehiclesListByDevicePropertyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetVehicleReportingGroupList", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVehicleReportingGroupList() As VehicleReportingGroup()
            Dim results() As Object = Me.Invoke("GetVehicleReportingGroupList", New Object(-1) {})
            Return CType(results(0),VehicleReportingGroup())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVehicleReportingGroupListAsync()
            Me.GetVehicleReportingGroupListAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVehicleReportingGroupListAsync(ByVal userState As Object)
            If (Me.GetVehicleReportingGroupListOperationCompleted Is Nothing) Then
                Me.GetVehicleReportingGroupListOperationCompleted = AddressOf Me.OnGetVehicleReportingGroupListOperationCompleted
            End If
            Me.InvokeAsync("GetVehicleReportingGroupList", New Object(-1) {}, Me.GetVehicleReportingGroupListOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVehicleReportingGroupListOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVehicleReportingGroupListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVehicleReportingGroupListCompleted(Me, New GetVehicleReportingGroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/GetVehicleReportingGroup", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetVehicleReportingGroup(ByVal GroupID As Integer) As VehicleReportingGroup
            Dim results() As Object = Me.Invoke("GetVehicleReportingGroup", New Object() {GroupID})
            Return CType(results(0),VehicleReportingGroup)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetVehicleReportingGroupAsync(ByVal GroupID As Integer)
            Me.GetVehicleReportingGroupAsync(GroupID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetVehicleReportingGroupAsync(ByVal GroupID As Integer, ByVal userState As Object)
            If (Me.GetVehicleReportingGroupOperationCompleted Is Nothing) Then
                Me.GetVehicleReportingGroupOperationCompleted = AddressOf Me.OnGetVehicleReportingGroupOperationCompleted
            End If
            Me.InvokeAsync("GetVehicleReportingGroup", New Object() {GroupID}, Me.GetVehicleReportingGroupOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetVehicleReportingGroupOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetVehicleReportingGroupCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetVehicleReportingGroupCompleted(Me, New GetVehicleReportingGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/ReportingGroupAddVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportingGroupAddVehicle(ByVal GroupID As Integer, ByVal VehicleID As Short) As Boolean
            Dim results() As Object = Me.Invoke("ReportingGroupAddVehicle", New Object() {GroupID, VehicleID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupAddVehicleAsync(ByVal GroupID As Integer, ByVal VehicleID As Short)
            Me.ReportingGroupAddVehicleAsync(GroupID, VehicleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupAddVehicleAsync(ByVal GroupID As Integer, ByVal VehicleID As Short, ByVal userState As Object)
            If (Me.ReportingGroupAddVehicleOperationCompleted Is Nothing) Then
                Me.ReportingGroupAddVehicleOperationCompleted = AddressOf Me.OnReportingGroupAddVehicleOperationCompleted
            End If
            Me.InvokeAsync("ReportingGroupAddVehicle", New Object() {GroupID, VehicleID}, Me.ReportingGroupAddVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportingGroupAddVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportingGroupAddVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportingGroupAddVehicleCompleted(Me, New ReportingGroupAddVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("TokenHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.omnibridge.com/SDKWebServices/AssetData/ReportingGroupRemoveVehicle", RequestNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", ResponseNamespace:="http://www.omnibridge.com/SDKWebServices/AssetData", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportingGroupRemoveVehicle(ByVal GroupID As Integer, ByVal VehicleID As Short) As Boolean
            Dim results() As Object = Me.Invoke("ReportingGroupRemoveVehicle", New Object() {GroupID, VehicleID})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupRemoveVehicleAsync(ByVal GroupID As Integer, ByVal VehicleID As Short)
            Me.ReportingGroupRemoveVehicleAsync(GroupID, VehicleID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportingGroupRemoveVehicleAsync(ByVal GroupID As Integer, ByVal VehicleID As Short, ByVal userState As Object)
            If (Me.ReportingGroupRemoveVehicleOperationCompleted Is Nothing) Then
                Me.ReportingGroupRemoveVehicleOperationCompleted = AddressOf Me.OnReportingGroupRemoveVehicleOperationCompleted
            End If
            Me.InvokeAsync("ReportingGroupRemoveVehicle", New Object() {GroupID, VehicleID}, Me.ReportingGroupRemoveVehicleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportingGroupRemoveVehicleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportingGroupRemoveVehicleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportingGroupRemoveVehicleCompleted(Me, New ReportingGroupRemoveVehicleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData", IsNullable:=false)>  _
    Partial Public Class TokenHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private tokenField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class ReportingGroupMember
        
        Private idField As Short
        
        Private displayNameField As String
        
        Private siteField As String
        
        '''<remarks/>
        Public Property ID() As Short
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Site() As String
            Get
                Return Me.siteField
            End Get
            Set
                Me.siteField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class VehicleReportingGroup
        
        Private vehiclesField() As ReportingGroupMember
        
        Private idField As Integer
        
        Private nameField As String
        
        Private notesField As String
        
        '''<remarks/>
        Public Property Vehicles() As ReportingGroupMember()
            Get
                Return Me.vehiclesField
            End Get
            Set
                Me.vehiclesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Vehicle)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public MustInherit Class EntityBase
        
        Private idField As String
        
        '''<remarks/>
        Public Property ID() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Partial Public Class Vehicle
        Inherits EntityBase
        
        Private siteIDField As Integer
        
        Private groupIDField As Integer
        
        Private descriptionField As String
        
        Private registrationNumberField As String
        
        Private unitTypeField As UnitTypes
        
        Private vehicleIconField As String
        
        Private targetFuelConsumptionField As Single
        
        Private targetHourlyConsumptionField As Single
        
        Private defaultDriverIDField As Short
        
        Private lastUpdateField As Date
        
        Private distanceCheckedField As Date
        
        Private lastOdometerField As Single
        
        Private lastTripField As Date
        
        Private lastEngineSecondsField As Integer
        
        Private lastServiceKeyField As Integer
        
        Private nextServiceKmField As Single
        
        Private serviceKmField As Single
        
        Private remindKmField As Single
        
        Private remindKm2Field As Single
        
        Private nextServiceDateField As Date
        
        Private serviceMonthsField As Byte
        
        Private remindWeeksField As Byte
        
        Private remindWeeks2Field As Byte
        
        Private nextServiceSecondsField As Integer
        
        Private serviceSecondsField As Integer
        
        Private remindSecondsField As Integer
        
        Private remindSeconds2Field As Integer
        
        Private lastLicenseField As Date
        
        Private nextLicenseField As Date
        
        Private licenseIntervalField As Byte
        
        Private licenseRemindField As Byte
        
        Private licenseRemind2Field As Byte
        
        Private lastCORField As Date
        
        Private nextCORField As Date
        
        Private cORIntervalField As Byte
        
        Private cORRemindField As Byte
        
        Private cORRemind2Field As Byte
        
        Private ignoreLateDownloadField As Boolean
        
        Private remindOnDistanceField As Boolean
        
        Private remindOnDurationField As Boolean
        
        Private serviceHoursField As Boolean
        
        Private licenseField As Boolean
        
        Private cORField As Boolean
        
        Private defaultAllowDriverAccessField As Boolean
        
        Private createdField As Date
        
        Private activeField As Boolean
        
        Private activeReasonField As String
        
        Private activeStateField As Byte
        
        '''<remarks/>
        Public Property SiteID() As Integer
            Get
                Return Me.siteIDField
            End Get
            Set
                Me.siteIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property GroupID() As Integer
            Get
                Return Me.groupIDField
            End Get
            Set
                Me.groupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RegistrationNumber() As String
            Get
                Return Me.registrationNumberField
            End Get
            Set
                Me.registrationNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UnitType() As UnitTypes
            Get
                Return Me.unitTypeField
            End Get
            Set
                Me.unitTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VehicleIcon() As String
            Get
                Return Me.vehicleIconField
            End Get
            Set
                Me.vehicleIconField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TargetFuelConsumption() As Single
            Get
                Return Me.targetFuelConsumptionField
            End Get
            Set
                Me.targetFuelConsumptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TargetHourlyConsumption() As Single
            Get
                Return Me.targetHourlyConsumptionField
            End Get
            Set
                Me.targetHourlyConsumptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DefaultDriverID() As Short
            Get
                Return Me.defaultDriverIDField
            End Get
            Set
                Me.defaultDriverIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastUpdate() As Date
            Get
                Return Me.lastUpdateField
            End Get
            Set
                Me.lastUpdateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DistanceChecked() As Date
            Get
                Return Me.distanceCheckedField
            End Get
            Set
                Me.distanceCheckedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastOdometer() As Single
            Get
                Return Me.lastOdometerField
            End Get
            Set
                Me.lastOdometerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastTrip() As Date
            Get
                Return Me.lastTripField
            End Get
            Set
                Me.lastTripField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastEngineSeconds() As Integer
            Get
                Return Me.lastEngineSecondsField
            End Get
            Set
                Me.lastEngineSecondsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastServiceKey() As Integer
            Get
                Return Me.lastServiceKeyField
            End Get
            Set
                Me.lastServiceKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NextServiceKm() As Single
            Get
                Return Me.nextServiceKmField
            End Get
            Set
                Me.nextServiceKmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceKm() As Single
            Get
                Return Me.serviceKmField
            End Get
            Set
                Me.serviceKmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindKm() As Single
            Get
                Return Me.remindKmField
            End Get
            Set
                Me.remindKmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindKm2() As Single
            Get
                Return Me.remindKm2Field
            End Get
            Set
                Me.remindKm2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NextServiceDate() As Date
            Get
                Return Me.nextServiceDateField
            End Get
            Set
                Me.nextServiceDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceMonths() As Byte
            Get
                Return Me.serviceMonthsField
            End Get
            Set
                Me.serviceMonthsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindWeeks() As Byte
            Get
                Return Me.remindWeeksField
            End Get
            Set
                Me.remindWeeksField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindWeeks2() As Byte
            Get
                Return Me.remindWeeks2Field
            End Get
            Set
                Me.remindWeeks2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NextServiceSeconds() As Integer
            Get
                Return Me.nextServiceSecondsField
            End Get
            Set
                Me.nextServiceSecondsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceSeconds() As Integer
            Get
                Return Me.serviceSecondsField
            End Get
            Set
                Me.serviceSecondsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindSeconds() As Integer
            Get
                Return Me.remindSecondsField
            End Get
            Set
                Me.remindSecondsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindSeconds2() As Integer
            Get
                Return Me.remindSeconds2Field
            End Get
            Set
                Me.remindSeconds2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastLicense() As Date
            Get
                Return Me.lastLicenseField
            End Get
            Set
                Me.lastLicenseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NextLicense() As Date
            Get
                Return Me.nextLicenseField
            End Get
            Set
                Me.nextLicenseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LicenseInterval() As Byte
            Get
                Return Me.licenseIntervalField
            End Get
            Set
                Me.licenseIntervalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LicenseRemind() As Byte
            Get
                Return Me.licenseRemindField
            End Get
            Set
                Me.licenseRemindField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LicenseRemind2() As Byte
            Get
                Return Me.licenseRemind2Field
            End Get
            Set
                Me.licenseRemind2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LastCOR() As Date
            Get
                Return Me.lastCORField
            End Get
            Set
                Me.lastCORField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NextCOR() As Date
            Get
                Return Me.nextCORField
            End Get
            Set
                Me.nextCORField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CORInterval() As Byte
            Get
                Return Me.cORIntervalField
            End Get
            Set
                Me.cORIntervalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CORRemind() As Byte
            Get
                Return Me.cORRemindField
            End Get
            Set
                Me.cORRemindField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CORRemind2() As Byte
            Get
                Return Me.cORRemind2Field
            End Get
            Set
                Me.cORRemind2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IgnoreLateDownload() As Boolean
            Get
                Return Me.ignoreLateDownloadField
            End Get
            Set
                Me.ignoreLateDownloadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindOnDistance() As Boolean
            Get
                Return Me.remindOnDistanceField
            End Get
            Set
                Me.remindOnDistanceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RemindOnDuration() As Boolean
            Get
                Return Me.remindOnDurationField
            End Get
            Set
                Me.remindOnDurationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ServiceHours() As Boolean
            Get
                Return Me.serviceHoursField
            End Get
            Set
                Me.serviceHoursField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property License() As Boolean
            Get
                Return Me.licenseField
            End Get
            Set
                Me.licenseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property COR() As Boolean
            Get
                Return Me.cORField
            End Get
            Set
                Me.cORField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DefaultAllowDriverAccess() As Boolean
            Get
                Return Me.defaultAllowDriverAccessField
            End Get
            Set
                Me.defaultAllowDriverAccessField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Created() As Date
            Get
                Return Me.createdField
            End Get
            Set
                Me.createdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Active() As Boolean
            Get
                Return Me.activeField
            End Get
            Set
                Me.activeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActiveReason() As String
            Get
                Return Me.activeReasonField
            End Get
            Set
                Me.activeReasonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ActiveState() As Byte
            Get
                Return Me.activeStateField
            End Get
            Set
                Me.activeStateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Public Enum UnitTypes
        
        '''<remarks/>
        FM1000
        
        '''<remarks/>
        FM200
        
        '''<remarks/>
        FM2000
        
        '''<remarks/>
        FM2100
        
        '''<remarks/>
        FM2300
        
        '''<remarks/>
        FM2200
        
        '''<remarks/>
        FM2001
        
        '''<remarks/>
        FM2000HV
        
        '''<remarks/>
        FM2100HV
        
        '''<remarks/>
        FM2300HV
        
        '''<remarks/>
        FM2200HV
        
        '''<remarks/>
        FM2001HV
        
        '''<remarks/>
        FM3310
        
        '''<remarks/>
        FM3210
        
        '''<remarks/>
        FM3311
        
        '''<remarks/>
        FM3211
        
        '''<remarks/>
        FM3316
        
        '''<remarks/>
        FM3310i
        
        '''<remarks/>
        FM3316i
        
        '''<remarks/>
        FM3106
        
        '''<remarks/>
        FM3517i
        
        '''<remarks/>
        FM3516i
        
        '''<remarks/>
        FM3617i
        
        '''<remarks/>
        FM3616i
        
        '''<remarks/>
        FM3717i
        
        '''<remarks/>
        FM3716i
        
        '''<remarks/>
        FM3817i
        
        '''<remarks/>
        FM3315
        
        '''<remarks/>
        MIX6000
        
        '''<remarks/>
        TrackTrace
        
        '''<remarks/>
        TrackTraceVt1330
        
        '''<remarks/>
        TrackTraceVt1300
        
        '''<remarks/>
        TrackTraceAt1330
        
        '''<remarks/>
        TrackTraceAt1340
        
        '''<remarks/>
        TrackTraceVt1305
        
        '''<remarks/>
        TrackTraceST2400
        
        '''<remarks/>
        TrackTraceST2410
        
        '''<remarks/>
        TrackTraceST3410
        
        '''<remarks/>
        TrackTracePT4310
        
        '''<remarks/>
        TrackTraceST4600
        
        '''<remarks/>
        TrackTraceST4700
        
        '''<remarks/>
        MIX2310i
        
        '''<remarks/>
        MIX2316
        
        '''<remarks/>
        MIX2416
        
        '''<remarks/>
        G52S
        
        '''<remarks/>
        RB100
        
        '''<remarks/>
        RB110
        
        '''<remarks/>
        RB200
        
        '''<remarks/>
        RB210
        
        '''<remarks/>
        RB300
        
        '''<remarks/>
        RB310
        
        '''<remarks/>
        NoUnit
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Public Enum VehicleActiveState
        
        '''<remarks/>
        Inactive
        
        '''<remarks/>
        Active
        
        '''<remarks/>
        BenchTested
        
        '''<remarks/>
        Decommissioned
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.omnibridge.com/SDKWebServices/AssetData")>  _
    Public Enum VehicleSearchOption
        
        '''<remarks/>
        Registration
        
        '''<remarks/>
        Description
        
        '''<remarks/>
        VehicleId
        
        '''<remarks/>
        UnitSerialNo
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AddBasicVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As AddBasicVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddBasicVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Short
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Short)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub AddVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As AddVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Short
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Short)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub UpdateVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub UpdateVehicleActiveStateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateVehicleActiveStateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateVehicleActiveStateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub DeleteVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As GetVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Vehicle
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Vehicle)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetVehiclesListCompletedEventHandler(ByVal sender As Object, ByVal e As GetVehiclesListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVehiclesListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Vehicle()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Vehicle())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetVehiclesListFilteredCompletedEventHandler(ByVal sender As Object, ByVal e As GetVehiclesListFilteredCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVehiclesListFilteredCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Vehicle()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Vehicle())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetVehiclesListByDevicePropertyCompletedEventHandler(ByVal sender As Object, ByVal e As GetVehiclesListByDevicePropertyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVehiclesListByDevicePropertyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Vehicle()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Vehicle())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetVehicleReportingGroupListCompletedEventHandler(ByVal sender As Object, ByVal e As GetVehicleReportingGroupListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVehicleReportingGroupListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VehicleReportingGroup()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VehicleReportingGroup())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetVehicleReportingGroupCompletedEventHandler(ByVal sender As Object, ByVal e As GetVehicleReportingGroupCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetVehicleReportingGroupCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As VehicleReportingGroup
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),VehicleReportingGroup)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReportingGroupAddVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As ReportingGroupAddVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportingGroupAddVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub ReportingGroupRemoveVehicleCompletedEventHandler(ByVal sender As Object, ByVal e As ReportingGroupRemoveVehicleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportingGroupRemoveVehicleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
